name: "Add or Update PR Comment"
description: "Add or update a PR comment identified by a comment type to avoid duplicates"
inputs:
  comment-type:
    description: "Unique identifier for the comment type (e.g., cycle_dependency, alpha_version)"
    required: true
  comment-body:
    description: "The body of the comment to post"
    required: true
  github-token:
    description: "GitHub token for API access"
    required: true
    default: ${{ github.token }}
  pr-number:
    description: "PR number (defaults to context.issue.number)"
    required: false
  condition:
    description: 'Condition to check before posting comment (e.g., "true" or "false")'
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Add or Update PR Comment
      if: inputs.condition == 'true' && github.event_name == 'pull_request'
      env:
        COMMENT_TYPE: ${{ inputs.comment-type }}
        COMMENT_BODY: ${{ inputs.comment-body }}
        PR_NUMBER: ${{ inputs.pr-number }}
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const commentType = process.env.COMMENT_TYPE;
          const commentBody = process.env.COMMENT_BODY || '';
          const inputPrNumber = process.env.PR_NUMBER;
          const prNumber = inputPrNumber && inputPrNumber.trim() !== '' 
            ? parseInt(inputPrNumber) 
            : context.issue.number;

          // Create a unique identifier for this comment type
          const commentIdentifier = `<!-- comment-type: ${commentType} -->`;

          if (!commentBody || commentBody.trim() === '') {
            core.info(`No comment body provided for type: ${commentType}`);
            return;
          }

          // Add the identifier to the comment body (hidden HTML comment)
          const fullCommentBody = `${commentIdentifier}\n${commentBody}`;

          try {
            // Get all comments on the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });
            
            // Find existing comment with this type
            const existingComment = comments.find(comment => 
              comment.body && comment.body.includes(commentIdentifier)
            );
            
            if (existingComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: fullCommentBody
              });
              core.info(`Updated existing comment for type: ${commentType}`);
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: fullCommentBody
              });
              core.info(`Created new comment for type: ${commentType}`);
            }
          } catch (error) {
            core.error(`Failed to add/update comment for type ${commentType}: ${error.message}`);
            throw error;
          }
