name: "Publish release branch"
description: "Create and publish package in a release branch"

inputs:
  branch-name:
    description: "Branch name"
    required: true
  directory:
    description: "Directory to publish"
    required: true
runs:
  using: "composite"
  steps:
    - name: Publish to release branch ${{ inputs.branch-name }}
      id: publish
      shell: bash
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        # Get the current commit SHA
        echo "Getting current commit SHA"
        SHA=$(git rev-parse --short HEAD)
        echo "Current commit SHA: $SHA"

        # Update package.json dependencies
        echo "Entering directory: ${{ inputs.directory }}"
        cd ${{ inputs.directory }}

        # Replace workspace:* dependencies with latest
        echo "Updating dependencies: Replace 'workspace:*' with 'latest'"
        sed -i 's/"workspace:\*"/"latest"/g' package.json

        # # Get current version from package.json
        # CURRENT_VERSION=$(node -p "require('./package.json').version")

        # # Update version to include alpha and SHA
        # npm version --no-git-tag-version "${CURRENT_VERSION}-alpha.${SHA}"

        cd -

        echo "Current directory: $(pwd)"
        git status

        echo "Adding all changes"
        git add -A

        echo "Committing changes"
        # If nothing to commit, skip
        git commit -m "chore: update dependencies" || echo "No changes to commit. Continuing..."

        echo "Publishing branch"
        # Publish alpha version
        pnpx sergiocarracedo/git-publish#npm/feat/directory-support -b '${{ inputs.branch-name }}' --directory ${{ inputs.directory }}

        # Get the latest commit SHA from the branch
        LAST=$(git log -n 1 'origin/${{ inputs.branch-name }}' --pretty=format:"%H")

        # Set output for use in next step
        echo "LAST_COMMIT_SHA=${LAST}" >> $GITHUB_OUTPUT

        # Print the message
        echo "::notice title='Package published'::Use pnpm i github:factorialco/f0#${{ inputs.branch-name }} to install the package (or pnpm i github:factorialco/f0#${LAST} to install this specific commit)"

    - name: Add PR comment with package installation instructions
      if: github.event_name == 'pull_request'
      uses: ./.github/actions/add-or-update-pr-comment
      with:
        comment-type: alpha_version
        github-token: ${{ github.token }}
        pr-number: ${{ github.event.pull_request.number }}
        comment-body: |
          ## 📦 Alpha Package Version Published

          Use `pnpm i github:factorialco/f0#${{ inputs.branch-name }}` to install the package

          Use `pnpm i github:factorialco/f0#${{ steps.publish.outputs.LAST_COMMIT_SHA }}` to install this specific commit
