name: "Publish release branch"
description: "Create and publish package in a release branch"

inputs:
  branch-name:
    description: "Branch name"
    required: true
  directory:
    description: "Directory to publish"
    required: true
runs:
  using: "composite"
  steps:
    - name: Publish to release branch ${{ inputs.branch-name }}
      shell: bash
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        # Publish alpha version
        pnpx sergiocarracedo/git-publish#npm/feat/directory-support -b '${{ inputs.branch-name }}' --directory ${{ inputs.directory }}
        LAST=$(git log -n 1 'origin/${{ inputs.branch-name }}' --pretty=format:"%H")
        echo "::notice title='Package published'::Use pnpm i github:factorialco/factorial-one#${{ inputs.branch-name }} to install the package (or pnpm i github:factorialco/factorial-one#${LAST} to install this specific commit)"
