# Validate commit messages
commit-msg:
  commands:
    "lint commit message":
      run: pnpm exec commitlint --edit {1}

pre-commit:
  commands:
    lint:
      run: pnpm lint {staged_files} --fix
      stage_fixed: true
    tsc:
      run: pnpm tsc {staged_files}