export interface FactorialOrgCell {
  role: string
  domain: string
  personName: string
  location: string
  startDate?: string
  isVacant: boolean
  isInterim: boolean
  isNewJoiner: boolean
  slackChannel?: string
  githubTeam?: string
  firefighterHandle?: string
  arrGoal?: number
  arrCurrent?: number
  customFieldProductMaturity?: "seed" | "growth" | "mature"
  customFieldTechStack?: string
}

export const factorialOrgData: FactorialOrgCell[] = [
  // TALENT DOMAIN
  {
    role: "Product Management",
    domain: "Talent",
    personName: "TBH",
    location: "",
    isVacant: true,
    isInterim: false,
    isNewJoiner: false,
    slackChannel: "#team-talent-pm",
    githubTeam: "talent-pm",
    firefighterHandle: "@talent-firefighter",
    arrGoal: 21500000,
    arrCurrent: 6738613,
    customFieldProductMaturity: "growth",
  },
  {
    role: "Product Design",
    domain: "Talent",
    personName: "Roberto Jimenez",
    location: "MAD",
    isVacant: false,
    isInterim: false,
    isNewJoiner: false,
    slackChannel: "#team-talent-design",
    githubTeam: "talent-design",
    arrGoal: 21500000,
    arrCurrent: 6738613,
    customFieldProductMaturity: "growth",
  },
  {
    role: "Product Engineering",
    domain: "Talent",
    personName: "Aamir Mughal",
    location: "BCN",
    isVacant: false,
    isInterim: false,
    isNewJoiner: true,
    startDate: "2026-05-11",
    slackChannel: "#team-talent-devs",
    githubTeam: "talent-engineering",
    firefighterHandle: "@talent-firefighter-devs",
    arrGoal: 21500000,
    arrCurrent: 6738613,
    customFieldProductMaturity: "growth",
    customFieldTechStack: "React, Ruby",
  },

  // FINANCE DOMAIN
  {
    role: "Product Management",
    domain: "Finance",
    personName: "TBH",
    location: "",
    isVacant: true,
    isInterim: false,
    isNewJoiner: false,
    slackChannel: "#team-finance-pm",
    githubTeam: "finance-pm",
    arrGoal: 8000000,
    arrCurrent: 5752816,
    customFieldProductMaturity: "mature",
  },
  {
    role: "Product Design",
    domain: "Finance",
    personName: "Lola Gimenez",
    location: "BCN",
    isVacant: false,
    isInterim: false,
    isNewJoiner: false,
    slackChannel: "#team-finance-design",
    githubTeam: "finance-design",
    arrGoal: 8000000,
    arrCurrent: 5752816,
    customFieldProductMaturity: "mature",
  },
  {
    role: "Product Engineering",
    domain: "Finance",
    personName: "Carlos Dominguez",
    location: "MAD",
    isVacant: false,
    isInterim: false,
    isNewJoiner: false,
    startDate: "2026-04-04",
    slackChannel: "#team-finance-devs",
    githubTeam: "finance-engineering",
    firefighterHandle: "@finance-firefighter-devs",
    arrGoal: 8000000,
    arrCurrent: 5752816,
    customFieldProductMaturity: "mature",
    customFieldTechStack: "React, Go",
  },
  {
    role: "Product Engineering",
    domain: "Finance",
    personName: "Pedro Ruiz",
    location: "MAD",
    isVacant: false,
    isInterim: false,
    isNewJoiner: false,
    startDate: "2026-04-20",
    slackChannel: "#team-finance-devs",
    githubTeam: "finance-engineering",
    firefighterHandle: "@finance-firefighter-devs",
    arrGoal: 8000000,
    arrCurrent: 5752816,
    customFieldProductMaturity: "mature",
    customFieldTechStack: "React, Go",
  },

  // TIME DOMAIN
  {
    role: "Product Management",
    domain: "Time",
    personName: "TBH",
    location: "",
    isVacant: true,
    isInterim: false,
    isNewJoiner: false,
    slackChannel: "#team-time-pm",
    githubTeam: "time-pm",
    arrGoal: 25000000,
    arrCurrent: 4821571,
    customFieldProductMaturity: "growth",
  },
  {
    role: "Product Design",
    domain: "Time",
    personName: "TBH",
    location: "",
    isVacant: true,
    isInterim: false,
    isNewJoiner: false,
    slackChannel: "#team-time-design",
    githubTeam: "time-design",
    arrGoal: 25000000,
    arrCurrent: 4821571,
    customFieldProductMaturity: "growth",
  },
  {
    role: "Product Engineering",
    domain: "Time",
    personName: "Pol Torrent",
    location: "BCN",
    isVacant: false,
    isInterim: false,
    isNewJoiner: true,
    startDate: "2026-05-11",
    slackChannel: "#team-time-devs",
    githubTeam: "time-engineering",
    firefighterHandle: "@time-firefighter-devs",
    arrGoal: 25000000,
    arrCurrent: 4821571,
    customFieldProductMaturity: "growth",
    customFieldTechStack: "React, Ruby",
  },

  // EMPLOYEE LIFECYCLE DOMAIN
  {
    role: "Product Management",
    domain: "Employee LifeCycle",
    personName: "TBH",
    location: "",
    isVacant: true,
    isInterim: false,
    isNewJoiner: false,
    slackChannel: "#team-lifecycle-pm",
    githubTeam: "lifecycle-pm",
    arrGoal: 12000000,
    arrCurrent: 6519132,
    customFieldProductMaturity: "seed",
  },
  {
    role: "Product Design",
    domain: "Employee LifeCycle",
    personName: "TBH",
    location: "",
    isVacant: true,
    isInterim: false,
    isNewJoiner: false,
    slackChannel: "#team-lifecycle-design",
    githubTeam: "lifecycle-design",
    arrGoal: 12000000,
    arrCurrent: 6519132,
    customFieldProductMaturity: "seed",
  },
  {
    role: "Product Engineering",
    domain: "Employee LifeCycle",
    personName: "Paula Rodriguez",
    location: "BCN",
    isVacant: false,
    isInterim: false,
    isNewJoiner: false,
    slackChannel: "#team-lifecycle-devs",
    githubTeam: "lifecycle-engineering",
    firefighterHandle: "@lifecycle-firefighter-devs",
    arrGoal: 12000000,
    arrCurrent: 6519132,
    customFieldProductMaturity: "seed",
    customFieldTechStack: "React, Ruby",
  },

  // PLATFORM DOMAIN
  {
    role: "Product Management",
    domain: "Platform",
    personName: "TBH",
    location: "",
    isVacant: true,
    isInterim: false,
    isNewJoiner: false,
    slackChannel: "#team-platform-pm",
    githubTeam: "platform-pm",
    arrGoal: 12500000,
    arrCurrent: 2466197,
    customFieldProductMaturity: "growth",
  },
  {
    role: "Product Design",
    domain: "Platform",
    personName: "TBH",
    location: "",
    isVacant: true,
    isInterim: false,
    isNewJoiner: false,
    slackChannel: "#team-platform-design",
    githubTeam: "platform-design",
    arrGoal: 12500000,
    arrCurrent: 2466197,
    customFieldProductMaturity: "growth",
  },
  {
    role: "Product Engineering",
    domain: "Platform",
    personName: "Gaston Rey",
    location: "BCN",
    isVacant: false,
    isInterim: true,
    isNewJoiner: false,
    slackChannel: "#team-platform-devs",
    githubTeam: "platform-engineering",
    firefighterHandle: "@platform-firefighter-devs",
    arrGoal: 12500000,
    arrCurrent: 2466197,
    customFieldProductMaturity: "growth",
    customFieldTechStack: "React, Rust, Go",
  },
  {
    role: "Product Engineering",
    domain: "Platform",
    personName: "Hugo Hajaali",
    location: "BCN",
    isVacant: false,
    isInterim: false,
    isNewJoiner: true,
    startDate: "2026-06-15",
    slackChannel: "#team-platform-devs",
    githubTeam: "platform-engineering",
    firefighterHandle: "@platform-firefighter-devs",
    arrGoal: 12500000,
    arrCurrent: 2466197,
    customFieldProductMaturity: "growth",
    customFieldTechStack: "React, Rust",
  },

  // GROWTH DOMAIN
  {
    role: "Product Management",
    domain: "Growth",
    personName: "TBH",
    location: "",
    isVacant: true,
    isInterim: false,
    isNewJoiner: false,
    slackChannel: "#team-growth-pm",
    githubTeam: "growth-pm",
    arrGoal: 8000000,
    arrCurrent: 4135000,
    customFieldProductMaturity: "seed",
  },
  {
    role: "Product Design",
    domain: "Growth",
    personName: "TBH",
    location: "",
    isVacant: true,
    isInterim: false,
    isNewJoiner: false,
    slackChannel: "#team-growth-design",
    githubTeam: "growth-design",
    arrGoal: 8000000,
    arrCurrent: 4135000,
    customFieldProductMaturity: "seed",
  },
  {
    role: "Product Engineering",
    domain: "Growth",
    personName: "Guilherme Cattani",
    location: "BCN",
    isVacant: false,
    isInterim: false,
    isNewJoiner: true,
    startDate: "2026-07-05",
    slackChannel: "#team-growth-devs",
    githubTeam: "growth-engineering",
    firefighterHandle: "@growth-firefighter-devs",
    arrGoal: 8000000,
    arrCurrent: 4135000,
    customFieldProductMaturity: "seed",
    customFieldTechStack: "React, Ruby",
  },
  {
    role: "Product Engineering",
    domain: "Growth",
    personName: "Andres Rojo",
    location: "BCN",
    isVacant: false,
    isInterim: false,
    isNewJoiner: true,
    startDate: "2026-05-11",
    slackChannel: "#team-growth-devs",
    githubTeam: "growth-engineering",
    firefighterHandle: "@growth-firefighter-devs",
    arrGoal: 8000000,
    arrCurrent: 4135000,
    customFieldProductMaturity: "seed",
    customFieldTechStack: "React, Ruby",
  },
]
