export interface MockEmployee {
  id: string
  fullName: string
  managerId: string | null
  team: string
  department: string
  tenureYears: number
  salary: number
  goalCompletion: number
  isManager: boolean
  avatarUrl?: string
}

export const mockedEmployees: MockEmployee[] = [
  {
    id: "1",
    fullName: "Alice CEO",
    managerId: null,
    team: "Leadership",
    department: "Executive",
    tenureYears: 8,
    salary: 200000,
    goalCompletion: 85,
    isManager: true,
  },
  {
    id: "2",
    fullName: "Bob VP Engineering",
    managerId: "1",
    team: "Engineering",
    department: "Product",
    tenureYears: 6,
    salary: 150000,
    goalCompletion: 90,
    isManager: true,
  },
  {
    id: "3",
    fullName: "Carol VP Sales",
    managerId: "1",
    team: "Sales",
    department: "Revenue",
    tenureYears: 5,
    salary: 160000,
    goalCompletion: 78,
    isManager: true,
  },
  {
    id: "4",
    fullName: "Dan Engineering Manager",
    managerId: "2",
    team: "Platform",
    department: "Product",
    tenureYears: 4,
    salary: 120000,
    goalCompletion: 92,
    isManager: true,
  },
  {
    id: "5",
    fullName: "Eve Senior Developer",
    managerId: "4",
    team: "Platform",
    department: "Product",
    tenureYears: 3,
    salary: 100000,
    goalCompletion: 88,
    isManager: false,
  },
  {
    id: "6",
    fullName: "Frank Developer",
    managerId: "4",
    team: "Platform",
    department: "Product",
    tenureYears: 1,
    salary: 80000,
    goalCompletion: 75,
    isManager: false,
  },
  {
    id: "7",
    fullName: "Grace Sales Lead",
    managerId: "3",
    team: "Enterprise",
    department: "Revenue",
    tenureYears: 4,
    salary: 130000,
    goalCompletion: 82,
    isManager: true,
  },
  {
    id: "8",
    fullName: "Henry Account Executive",
    managerId: "7",
    team: "Enterprise",
    department: "Revenue",
    tenureYears: 2,
    salary: 90000,
    goalCompletion: 70,
    isManager: false,
  },
  {
    id: "9",
    fullName: "Ivy Account Executive",
    managerId: "7",
    team: "Enterprise",
    department: "Revenue",
    tenureYears: 1,
    salary: 85000,
    goalCompletion: 65,
    isManager: false,
  },
  {
    id: "10",
    fullName: "Jack VP Marketing",
    managerId: "1",
    team: "Marketing",
    department: "Growth",
    tenureYears: 4,
    salary: 140000,
    goalCompletion: 80,
    isManager: true,
  },
  {
    id: "11",
    fullName: "Kate Marketing Manager",
    managerId: "10",
    team: "Content",
    department: "Growth",
    tenureYears: 3,
    salary: 110000,
    goalCompletion: 85,
    isManager: true,
  },
  {
    id: "12",
    fullName: "Liam Content Writer",
    managerId: "11",
    team: "Content",
    department: "Growth",
    tenureYears: 2,
    salary: 75000,
    goalCompletion: 90,
    isManager: false,
  },
  {
    id: "13",
    fullName: "Mia Designer",
    managerId: "11",
    team: "Content",
    department: "Growth",
    tenureYears: 1,
    salary: 70000,
    goalCompletion: 88,
    isManager: false,
  },
  {
    id: "14",
    fullName: "Noah Engineering Manager",
    managerId: "2",
    team: "Mobile",
    department: "Product",
    tenureYears: 5,
    salary: 125000,
    goalCompletion: 95,
    isManager: true,
  },
  {
    id: "15",
    fullName: "Olivia Mobile Developer",
    managerId: "14",
    team: "Mobile",
    department: "Product",
    tenureYears: 2,
    salary: 95000,
    goalCompletion: 80,
    isManager: false,
  },
  {
    id: "16",
    fullName: "Paul Mobile Developer",
    managerId: "14",
    team: "Mobile",
    department: "Product",
    tenureYears: 1,
    salary: 85000,
    goalCompletion: 72,
    isManager: false,
  },
  {
    id: "17",
    fullName: "Quinn Sales Lead",
    managerId: "3",
    team: "SMB",
    department: "Revenue",
    tenureYears: 3,
    salary: 115000,
    goalCompletion: 76,
    isManager: true,
  },
  {
    id: "18",
    fullName: "Rachel Account Executive",
    managerId: "17",
    team: "SMB",
    department: "Revenue",
    tenureYears: 1,
    salary: 80000,
    goalCompletion: 68,
    isManager: false,
  },
  {
    id: "19",
    fullName: "Sam HR Manager",
    managerId: "1",
    team: "People",
    department: "Operations",
    tenureYears: 6,
    salary: 110000,
    goalCompletion: 92,
    isManager: true,
  },
  {
    id: "20",
    fullName: "Tina Recruiter",
    managerId: "19",
    team: "People",
    department: "Operations",
    tenureYears: 2,
    salary: 70000,
    goalCompletion: 85,
    isManager: false,
  },
]
