import type { GoalRecord } from "./types"

export const goalsFixtures: GoalRecord[] = [
  // ─── TEAM GOALS (shown in "Team goals" preset) ─────────────────────
  {
    id: "g-001",
    title: "Factorial ARR",
    assigneeId: "emp-002",
    status: "not-started",
    measure: "10.000€ → 15.000€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: ["g-002", "g-003"],
    scope: "team",
  },
  {
    id: "g-002",
    title: "Enhance store operations",
    assigneeId: "emp-002",
    status: "on-track",
    measure: "10.000€ → 15.000€",
    progress: 35,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "g-001",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "g-003",
    title: "Close €1M in Q1",
    assigneeId: "emp-002",
    status: "achieved",
    measure: "10.000€ → 15.000€",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "g-001",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "g-004",
    title: "Improve lead response time",
    assigneeId: "emp-003",
    status: "not-started",
    measure: "48h → 12h",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "team",
  },
  {
    id: "g-005",
    title: "Enhance HR and employee development",
    assigneeId: "emp-004",
    status: "cancelled",
    measure: "10.000€ → 15.000€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: ["g-006", "g-007", "g-008"],
    scope: "team",
  },
  {
    id: "g-006",
    title: "Increase pipeline by 20%",
    assigneeId: "emp-005",
    status: "not-started",
    measure: "10.000€ → 15.000€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "g-005",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "g-007",
    title: "Increase revenue by 20%",
    assigneeId: "emp-006",
    status: "not-started",
    measure: "10.000€ → 15.000€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "g-005",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "g-008",
    title: "Optimize development efficiency",
    assigneeId: "emp-007",
    status: "not-started",
    measure: "10.000€ → 15.000€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "g-005",
    childrenIds: ["g-009", "g-010"],
    scope: "team",
  },
  {
    id: "g-009",
    title: "Optimize sales performance",
    assigneeId: "emp-008",
    status: "not-started",
    measure: "10.000€ → 15.000€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "g-008",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "g-010",
    title: "Streamline internal processes",
    assigneeId: "emp-009",
    status: "not-started",
    measure: "10.000€ → 15.000€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "g-008",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "g-011",
    title: "Strengthen financial performance",
    assigneeId: "emp-010",
    status: "not-started",
    measure: "5M€ → 8M€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "team",
  },
  {
    id: "g-012",
    title: "Expand into new markets",
    assigneeId: "emp-011",
    status: "on-track",
    measure: "2 markets → 5 markets",
    progress: 40,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "team",
  },
  {
    id: "g-013",
    title: "Increase user engagement",
    assigneeId: "emp-012",
    status: "on-track",
    measure: "DAU 5k → 12k",
    progress: 55,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "team",
  },
  {
    id: "g-014",
    title: "Reduce operational costs",
    assigneeId: "emp-013",
    status: "not-started",
    measure: "15% reduction",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "team",
  },
  {
    id: "g-015",
    title: "Launch mobile app v2",
    assigneeId: "emp-014",
    status: "on-track",
    measure: "0 → 1 release",
    progress: 70,
    startDate: "2026-02-01",
    dueDate: "2026-05-31",
    parentId: null,
    childrenIds: [],
    scope: "team",
  },

  // ─── MY GOALS (shown in "My goals" preset) ─────────────────────────
  {
    id: "g-100",
    title: "Complete Q1 performance reviews",
    assigneeId: "emp-001",
    status: "achieved",
    measure: "15/15 reviews",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-101",
    title: "Ship payroll integration",
    assigneeId: "emp-001",
    status: "on-track",
    measure: "0 → 1 integration",
    progress: 60,
    startDate: "2026-01-15",
    dueDate: "2026-04-30",
    parentId: null,
    childrenIds: ["g-102", "g-103"],
    scope: "mine",
  },
  {
    id: "g-102",
    title: "API design and documentation",
    assigneeId: "emp-001",
    status: "achieved",
    measure: "0 → 1 spec",
    progress: 100,
    startDate: "2026-01-15",
    dueDate: "2026-02-28",
    parentId: "g-101",
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-103",
    title: "Backend implementation",
    assigneeId: "emp-001",
    status: "on-track",
    measure: "0 → 12 endpoints",
    progress: 50,
    startDate: "2026-03-01",
    dueDate: "2026-04-30",
    parentId: "g-101",
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-104",
    title: "Reduce bug backlog by 30%",
    assigneeId: "emp-001",
    status: "on-track",
    measure: "120 → 84 bugs",
    progress: 45,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-105",
    title: "Mentor 2 junior engineers",
    assigneeId: "emp-001",
    status: "on-track",
    measure: "0 → 2 mentees",
    progress: 50,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-106",
    title: "Obtain AWS certification",
    assigneeId: "emp-001",
    status: "not-started",
    measure: "0 → 1 cert",
    progress: 0,
    startDate: "2026-04-01",
    dueDate: "2026-09-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-107",
    title: "Improve team code review turnaround",
    assigneeId: "emp-001",
    status: "on-track",
    measure: "48h → 24h avg",
    progress: 30,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-108",
    title: "Write technical blog posts",
    assigneeId: "emp-001",
    status: "not-started",
    measure: "0 → 4 posts",
    progress: 0,
    startDate: "2026-03-01",
    dueDate: "2026-12-31",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-109",
    title: "Improve test coverage to 80%",
    assigneeId: "emp-001",
    status: "on-track",
    measure: "62% → 80%",
    progress: 55,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-110",
    title: "Lead architecture review sessions",
    assigneeId: "emp-001",
    status: "on-track",
    measure: "0 → 6 sessions",
    progress: 33,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-111",
    title: "Deliver sprint demos on time",
    assigneeId: "emp-001",
    status: "achieved",
    measure: "100% sprints",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },

  // ─── ALL GOALS (additional goals beyond team+mine) ──────────────────
  {
    id: "g-200",
    title: "Redesign onboarding experience",
    assigneeId: "emp-015",
    status: "on-track",
    measure: "NPS 40 → 70",
    progress: 60,
    startDate: "2026-01-01",
    dueDate: "2026-04-30",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-201",
    title: "Achieve SOC2 compliance",
    assigneeId: "emp-016",
    status: "on-track",
    measure: "0 → 1 audit passed",
    progress: 75,
    startDate: "2025-10-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-202",
    title: "Reduce churn rate",
    assigneeId: "emp-017",
    status: "not-started",
    measure: "5% → 3%",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: null,
    childrenIds: ["g-203", "g-204"],
    scope: "all",
  },
  {
    id: "g-203",
    title: "Implement customer health scoring",
    assigneeId: "emp-017",
    status: "on-track",
    measure: "0 → 1 system",
    progress: 40,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: "g-202",
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-204",
    title: "Launch proactive support program",
    assigneeId: "emp-018",
    status: "not-started",
    measure: "0 → 1 program",
    progress: 0,
    startDate: "2026-04-01",
    dueDate: "2026-09-30",
    parentId: "g-202",
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-205",
    title: "Build analytics dashboard",
    assigneeId: "emp-019",
    status: "on-track",
    measure: "0 → 1 dashboard",
    progress: 80,
    startDate: "2026-02-01",
    dueDate: "2026-04-30",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-206",
    title: "Migrate to new infrastructure",
    assigneeId: "emp-003",
    status: "on-track",
    measure: "0% → 100% migrated",
    progress: 45,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-207",
    title: "Launch partner program",
    assigneeId: "emp-014",
    status: "not-started",
    measure: "0 → 10 partners",
    progress: 0,
    startDate: "2026-04-01",
    dueDate: "2026-12-31",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-208",
    title: "Improve page load performance",
    assigneeId: "emp-005",
    status: "achieved",
    measure: "3.2s → 1.5s LCP",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-209",
    title: "Scale customer support",
    assigneeId: "emp-016",
    status: "on-track",
    measure: "2h → 30min response",
    progress: 50,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-210",
    title: "Implement AI-powered suggestions",
    assigneeId: "emp-007",
    status: "not-started",
    measure: "0 → 1 feature",
    progress: 0,
    startDate: "2026-05-01",
    dueDate: "2026-09-30",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-211",
    title: "Establish design system v2",
    assigneeId: "emp-009",
    status: "on-track",
    measure: "0 → 50 components",
    progress: 60,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-212",
    title: "Automate regression testing",
    assigneeId: "emp-006",
    status: "on-track",
    measure: "20% → 80% coverage",
    progress: 55,
    startDate: "2026-02-01",
    dueDate: "2026-07-31",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-213",
    title: "Grow engineering team",
    assigneeId: "emp-010",
    status: "on-track",
    measure: "25 → 40 engineers",
    progress: 40,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-214",
    title: "Implement GDPR data export",
    assigneeId: "emp-012",
    status: "achieved",
    measure: "0 → 1 feature",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-02-28",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-215",
    title: "Reduce deployment frequency gap",
    assigneeId: "emp-008",
    status: "on-track",
    measure: "weekly → daily",
    progress: 70,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
]

/** Get goals for a given scope (top-level only). */
export function getGoalsByScope(scope: "team" | "all" | "mine"): GoalRecord[] {
  if (scope === "all") {
    // "All goals" shows everything (top-level)
    return goalsFixtures.filter((g) => g.parentId === null)
  }
  return goalsFixtures.filter((g) => g.parentId === null && g.scope === scope)
}

/** Get children for a given goal id. */
export function getGoalChildren(parentId: string): GoalRecord[] {
  return goalsFixtures.filter((g) => g.parentId === parentId)
}

/** Count goals per scope (top-level only). */
export function getGoalCounts() {
  const all = goalsFixtures.filter((g) => g.parentId === null)
  const team = all.filter((g) => g.scope === "team")
  const mine = all.filter((g) => g.scope === "mine")
  return { team: team.length, all: all.length, mine: mine.length }
}
