import type { CompanyId } from "./companies"
import type { GoalRecord } from "./types"

// ═══════════════════════════════════════════════════════════════════════
// DEFAULT fixtures (the generic demo data that existed before)
// ═══════════════════════════════════════════════════════════════════════

const defaultGoals: GoalRecord[] = [
  // ─── TEAM GOALS ────────────────────────────────────────────────────
  {
    id: "g-001",
    title: "Factorial ARR",
    ownerId: "emp-002",
    assignee: { type: "company", name: "Factorial" },
    status: "at-risk",
    measure: "10.000€ → 15.000€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: ["g-002", "g-003"],
    scope: "team",
    incentivePlans: ["Product org incentive", "Directors incentive"],
  },
  {
    id: "g-002",
    title: "Enhance store operations",
    ownerId: "emp-002",
    assignee: { type: "team", teamId: "team-people-ops" },
    status: "on-track",
    measure: "10.000€ → 15.000€",
    progress: 35,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "g-001",
    childrenIds: [],
    scope: "team",
    incentivePlans: ["Managers incentive", "Directors incentive"],
  },
  {
    id: "g-003",
    title: "Close €1M in Q1",
    ownerId: "emp-002",
    assignee: { type: "group", employeeIds: ["emp-002", "emp-011", "emp-012"] },
    status: "achieved",
    measure: "10.000€ → 15.000€",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "g-001",
    childrenIds: [],
    scope: "team",
    incentivePlans: ["Performance team incentive"],
    actionPlans: ["Q1 sales push"],
  },
  {
    id: "g-004",
    title: "Improve lead response time",
    ownerId: "emp-003",
    assignee: { type: "team", teamId: "team-recruiting" },
    status: "on-track",
    measure: "48h → 12h",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "team",
    incentivePlans: ["Performance team incentive"],
  },
  {
    id: "g-005",
    title: "Enhance HR and employee development",
    ownerId: "emp-004",
    assignee: { type: "team", teamId: "team-people-ops" },
    status: "cancelled",
    measure: "10.000€ → 15.000€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: ["g-006", "g-007", "g-008"],
    scope: "team",
    incentivePlans: ["Performance team incentive"],
    actionPlans: ["HR transformation"],
  },
  {
    id: "g-006",
    title: "Increase pipeline by 20%",
    ownerId: "emp-005",
    assignee: { type: "group", employeeIds: ["emp-005", "emp-006"] },
    status: "partial",
    measure: "10.000€ → 15.000€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "g-005",
    childrenIds: [],
    scope: "team",
    incentivePlans: ["Performance team incentive"],
  },
  {
    id: "g-007",
    title: "Increase revenue by 20%",
    ownerId: "emp-006",
    assignee: { type: "team", teamId: "team-payroll" },
    status: "at-risk",
    measure: "10.000€ → 15.000€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "g-005",
    childrenIds: [],
    scope: "team",
    incentivePlans: ["Performance team incentive"],
  },
  {
    id: "g-008",
    title: "Optimize development efficiency",
    ownerId: "emp-007",
    assignee: { type: "team", teamId: "team-platform" },
    status: "on-track",
    measure: "10.000€ → 15.000€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "g-005",
    childrenIds: ["g-009", "g-010"],
    scope: "team",
    actionPlans: ["Engineering efficiency plan"],
  },
  {
    id: "g-009",
    title: "Optimize sales performance",
    ownerId: "emp-008",
    assignee: { type: "individual", employeeId: "emp-008" },
    status: "missed",
    measure: "10.000€ → 15.000€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "g-008",
    childrenIds: [],
    scope: "team",
    incentivePlans: ["Engagement team incentive"],
  },
  {
    id: "g-010",
    title: "Streamline internal processes",
    ownerId: "emp-009",
    assignee: { type: "group", employeeIds: ["emp-009", "emp-007"] },
    status: "partial",
    measure: "10.000€ → 15.000€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "g-008",
    childrenIds: [],
    scope: "team",
    incentivePlans: ["Performance team incentive"],
  },
  {
    id: "g-011",
    title: "Strengthen financial performance",
    ownerId: "emp-010",
    assignee: { type: "company", name: "Factorial" },
    status: "on-track",
    measure: "5M€ → 8M€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "team",
    incentivePlans: ["Performance team incentive"],
  },
  {
    id: "g-012",
    title: "Expand into new markets",
    ownerId: "emp-011",
    assignee: { type: "company", name: "Factorial" },
    status: "on-track",
    measure: "2 markets → 5 markets",
    progress: 40,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "team",
    incentivePlans: ["Performance team incentive"],
  },
  {
    id: "g-013",
    title: "Increase user engagement",
    ownerId: "emp-012",
    assignee: { type: "team", teamId: "team-design-product" },
    status: "on-track",
    measure: "DAU 5k → 12k",
    progress: 55,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "team",
    incentivePlans: ["Performance team incentive"],
  },
  {
    id: "g-014",
    title: "Reduce operational costs",
    ownerId: "emp-013",
    assignee: { type: "company", name: "Factorial" },
    status: "at-risk",
    measure: "15% reduction",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "team",
    incentivePlans: ["Performance team incentive"],
  },
  {
    id: "g-015",
    title: "Launch mobile app v2",
    ownerId: "emp-014",
    assignee: { type: "team", teamId: "team-platform" },
    status: "on-track",
    measure: "0 → 1 release",
    progress: 70,
    startDate: "2026-02-01",
    dueDate: "2026-05-31",
    parentId: null,
    childrenIds: [],
    scope: "team",
    incentivePlans: ["Performance team incentive"],
    actionPlans: ["Performance review"],
  },
  // ─── MY GOALS ──────────────────────────────────────────────────────
  {
    id: "g-100",
    title: "Complete Q1 performance reviews",
    ownerId: "emp-001",
    assignee: { type: "individual", employeeId: "emp-001" },
    status: "achieved",
    measure: "15/15 reviews",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "mine",
    incentivePlans: ["Performance team incentive"],
    actionPlans: ["Performance review"],
  },
  {
    id: "g-101",
    title: "Ship payroll integration",
    ownerId: "emp-001",
    assignee: { type: "team", teamId: "team-payroll" },
    status: "on-track",
    measure: "0 → 1 integration",
    progress: 60,
    startDate: "2026-01-15",
    dueDate: "2026-04-30",
    parentId: null,
    childrenIds: ["g-102", "g-103"],
    scope: "mine",
    incentivePlans: ["Performance team incentive"],
  },
  {
    id: "g-102",
    title: "API design and documentation",
    ownerId: "emp-001",
    assignee: { type: "individual", employeeId: "emp-001" },
    status: "achieved",
    measure: "0 → 1 spec",
    progress: 100,
    startDate: "2026-01-15",
    dueDate: "2026-02-28",
    parentId: "g-101",
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-103",
    title: "Backend implementation",
    ownerId: "emp-001",
    assignee: { type: "group", employeeIds: ["emp-001", "emp-004", "emp-005"] },
    status: "on-track",
    measure: "0 → 12 endpoints",
    progress: 50,
    startDate: "2026-03-01",
    dueDate: "2026-04-30",
    parentId: "g-101",
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-104",
    title: "Reduce bug backlog by 30%",
    ownerId: "emp-001",
    assignee: { type: "individual", employeeId: "emp-001" },
    status: "on-track",
    measure: "120 → 84 bugs",
    progress: 45,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-105",
    title: "Mentor 2 junior engineers",
    ownerId: "emp-001",
    assignee: { type: "individual", employeeId: "emp-001" },
    status: "on-track",
    measure: "0 → 2 mentees",
    progress: 50,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-106",
    title: "Obtain AWS certification",
    ownerId: "emp-001",
    assignee: { type: "individual", employeeId: "emp-001" },
    status: "on-track",
    measure: "0 → 1 cert",
    progress: 0,
    startDate: "2026-04-01",
    dueDate: "2026-09-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-107",
    title: "Improve team code review turnaround",
    ownerId: "emp-001",
    assignee: { type: "team", teamId: "team-eng-leadership" },
    status: "on-track",
    measure: "48h → 24h avg",
    progress: 30,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-108",
    title: "Write technical blog posts",
    ownerId: "emp-001",
    assignee: { type: "individual", employeeId: "emp-001" },
    status: "partial",
    measure: "0 → 4 posts",
    progress: 0,
    startDate: "2026-03-01",
    dueDate: "2026-12-31",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-109",
    title: "Improve test coverage to 80%",
    ownerId: "emp-001",
    assignee: { type: "team", teamId: "team-platform" },
    status: "on-track",
    measure: "62% → 80%",
    progress: 55,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-110",
    title: "Lead architecture review sessions",
    ownerId: "emp-001",
    assignee: { type: "team", teamId: "team-eng-leadership" },
    status: "on-track",
    measure: "0 → 6 sessions",
    progress: 33,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "g-111",
    title: "Deliver sprint demos on time",
    ownerId: "emp-001",
    assignee: { type: "individual", employeeId: "emp-001" },
    status: "achieved",
    measure: "100% sprints",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  // ─── ALL GOALS ─────────────────────────────────────────────────────
  {
    id: "g-200",
    title: "Redesign onboarding experience",
    ownerId: "emp-015",
    assignee: { type: "team", teamId: "team-design-product" },
    status: "on-track",
    measure: "NPS 40 → 70",
    progress: 60,
    startDate: "2026-01-01",
    dueDate: "2026-04-30",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-201",
    title: "Achieve SOC2 compliance",
    ownerId: "emp-016",
    assignee: { type: "company", name: "Factorial" },
    status: "on-track",
    measure: "0 → 1 audit passed",
    progress: 75,
    startDate: "2025-10-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-202",
    title: "Reduce churn rate",
    ownerId: "emp-017",
    assignee: { type: "company", name: "Factorial" },
    status: "missed",
    measure: "5% → 3%",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: null,
    childrenIds: ["g-203", "g-204"],
    scope: "all",
  },
  {
    id: "g-203",
    title: "Implement customer health scoring",
    ownerId: "emp-017",
    assignee: { type: "team", teamId: "team-time-off" },
    status: "on-track",
    measure: "0 → 1 system",
    progress: 40,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: "g-202",
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-204",
    title: "Launch proactive support program",
    ownerId: "emp-018",
    assignee: { type: "group", employeeIds: ["emp-018", "emp-017", "emp-012"] },
    status: "on-track",
    measure: "0 → 1 program",
    progress: 0,
    startDate: "2026-04-01",
    dueDate: "2026-09-30",
    parentId: "g-202",
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-205",
    title: "Build analytics dashboard",
    ownerId: "emp-019",
    assignee: { type: "team", teamId: "team-platform" },
    status: "on-track",
    measure: "0 → 1 dashboard",
    progress: 80,
    startDate: "2026-02-01",
    dueDate: "2026-04-30",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-206",
    title: "Migrate to new infrastructure",
    ownerId: "emp-003",
    assignee: { type: "team", teamId: "team-platform" },
    status: "on-track",
    measure: "0% → 100% migrated",
    progress: 45,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-207",
    title: "Launch partner program",
    ownerId: "emp-014",
    assignee: { type: "company", name: "Factorial" },
    status: "at-risk",
    measure: "0 → 10 partners",
    progress: 0,
    startDate: "2026-04-01",
    dueDate: "2026-12-31",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-208",
    title: "Improve page load performance",
    ownerId: "emp-005",
    assignee: { type: "team", teamId: "team-platform" },
    status: "achieved",
    measure: "3.2s → 1.5s LCP",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-209",
    title: "Scale customer support",
    ownerId: "emp-016",
    assignee: { type: "team", teamId: "team-people-ops" },
    status: "on-track",
    measure: "2h → 30min response",
    progress: 50,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-210",
    title: "Implement AI-powered suggestions",
    ownerId: "emp-007",
    assignee: { type: "group", employeeIds: ["emp-007", "emp-008", "emp-005"] },
    status: "partial",
    measure: "0 → 1 feature",
    progress: 0,
    startDate: "2026-05-01",
    dueDate: "2026-09-30",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-211",
    title: "Establish design system v2",
    ownerId: "emp-009",
    assignee: { type: "team", teamId: "team-design-systems" },
    status: "on-track",
    measure: "0 → 50 components",
    progress: 60,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-212",
    title: "Automate regression testing",
    ownerId: "emp-006",
    assignee: { type: "team", teamId: "team-platform" },
    status: "on-track",
    measure: "20% → 80% coverage",
    progress: 55,
    startDate: "2026-02-01",
    dueDate: "2026-07-31",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-213",
    title: "Grow engineering team",
    ownerId: "emp-010",
    assignee: { type: "company", name: "Factorial" },
    status: "on-track",
    measure: "25 → 40 engineers",
    progress: 40,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-214",
    title: "Implement GDPR data export",
    ownerId: "emp-012",
    assignee: { type: "team", teamId: "team-platform" },
    status: "achieved",
    measure: "0 → 1 feature",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-02-28",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
  {
    id: "g-215",
    title: "Reduce deployment frequency gap",
    ownerId: "emp-008",
    assignee: { type: "team", teamId: "team-platform" },
    status: "on-track",
    measure: "weekly → daily",
    progress: 70,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "all",
  },
]

// ═══════════════════════════════════════════════════════════════════════
// FACTORIAL fixtures — extracted from the Factorial production screenshot.
// Deep tree: Factorial ARR → Sales / Product & Eng / Talent / … with
// further nesting under Talent → Performance → Q1‥Q4, plus standalone
// top-level "SLA" goal. Also some "My goals" for the logged-in user.
// ═══════════════════════════════════════════════════════════════════════

const factorialGoals: GoalRecord[] = [
  // ─── TEAM GOALS ────────────────────────────────────────────────────
  // Root: Factorial ARR
  {
    id: "f-001",
    title: "Factorial ARR",
    ownerId: "emp-002",
    assignee: { type: "company", name: "Factorial" },
    status: "on-track",
    measure: "150.000.000€",
    progress: 14,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: null,
    childrenIds: [
      "f-010",
      "f-020",
      "f-030",
      "f-060",
      "f-070",
      "f-080",
      "f-090",
      "f-100",
      "f-110",
      "f-120",
      "f-130",
    ],
    scope: "team",
  },

  // ── L1: Factorial ARR - Sales
  {
    id: "f-010",
    title: "Factorial ARR - Sales",
    ownerId: "emp-014",
    assignee: { type: "department", departmentId: "dept-sales" },
    status: "on-track",
    measure: "-€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-001",
    childrenIds: [],
    scope: "team",
  },

  // ── L1: Factorial ARR - Product & Eng
  {
    id: "f-020",
    title: "Factorial ARR - Product & Eng",
    ownerId: "emp-001",
    assignee: { type: "area", name: "Product & Eng" },
    status: "on-track",
    measure: "70.556.331€",
    progress: 17,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-001",
    childrenIds: [],
    scope: "team",
  },

  // ── L1: Factorial ARR - Talent  (has children: Performance, Engagement, …)
  {
    id: "f-030",
    title: "Factorial ARR - Talent",
    ownerId: "emp-002",
    assignee: { type: "area", name: "Talent" },
    status: "on-track",
    measure: "21.251.821€",
    progress: 20,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-001",
    childrenIds: ["f-031", "f-040", "f-041", "f-042", "f-043", "f-044"],
    scope: "team",
  },

  // ─── L2: Factorial ARR - Performance (under Talent)
  {
    id: "f-031",
    title: "Factorial ARR - Performance",
    ownerId: "emp-004",
    assignee: { type: "area", name: "Performance" },
    status: "on-track",
    measure: "6.738.613 €",
    progress: 43,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-030",
    childrenIds: ["f-032", "f-033", "f-034", "f-035"],
    scope: "team",
  },

  // ─── L3: Quarterly breakdown under Performance
  {
    id: "f-032",
    title: "Factorial ARR - Performance - Q1",
    ownerId: "emp-004",
    assignee: { type: "area", name: "Performance" },
    status: "achieved",
    measure: "1.010.792 €",
    progress: 158,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "f-031",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "f-033",
    title: "Factorial ARR - Performance - Q2",
    ownerId: "emp-004",
    assignee: { type: "area", name: "Performance" },
    status: "on-track",
    measure: "1.482.495 €",
    progress: 15,
    startDate: "2026-04-01",
    dueDate: "2026-06-30",
    parentId: "f-031",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "f-034",
    title: "Factorial ARR - Performance - Q3",
    ownerId: "emp-004",
    assignee: { type: "area", name: "Performance" },
    status: "on-track",
    measure: "1.347.723 €",
    progress: 0,
    startDate: "2026-07-01",
    dueDate: "2026-09-30",
    parentId: "f-031",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "f-035",
    title: "Factorial ARR - Performance - Q4",
    ownerId: "emp-004",
    assignee: { type: "area", name: "Performance" },
    status: "missed",
    measure: "2.897.603 €",
    progress: 0,
    startDate: "2026-10-01",
    dueDate: "2026-12-31",
    parentId: "f-031",
    childrenIds: [],
    scope: "team",
  },

  // ─── L2: Engagement, Trust channel, Recruitment, Training, LMS (under Talent)
  {
    id: "f-040",
    title: "Factorial ARR - Engagement",
    ownerId: "emp-012",
    assignee: { type: "area", name: "Engagement" },
    status: "on-track",
    measure: "5.752.816 €",
    progress: 12,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-030",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "f-041",
    title: "Factorial ARR - Trust channel",
    ownerId: "emp-016",
    assignee: { type: "area", name: "Trust channel" },
    status: "on-track",
    measure: "1.953.209 €",
    progress: 42,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-030",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "f-042",
    title: "Factorial ARR - Recruitment",
    ownerId: "emp-003",
    assignee: { type: "area", name: "Recruitment" },
    status: "on-track",
    measure: "4.821.571 €",
    progress: 11,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-030",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "f-043",
    title: "Factorial ARR - Training",
    ownerId: "emp-007",
    assignee: { type: "area", name: "Training" },
    status: "on-track",
    measure: "6.519.132 €",
    progress: 18,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-030",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "f-044",
    title: "Factorial ARR - LMS",
    ownerId: "emp-005",
    assignee: { type: "area", name: "LMS" },
    status: "on-track",
    measure: "2.466.197 €",
    progress: 30,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-030",
    childrenIds: [],
    scope: "team",
  },

  // ── L1: Factorial ARR - Finance
  {
    id: "f-060",
    title: "Factorial ARR - Finance",
    ownerId: "emp-010",
    assignee: { type: "area", name: "Finance" },
    status: "on-track",
    measure: "9.008.900€",
    progress: 11,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-001",
    childrenIds: [],
    scope: "team",
  },

  // ── L1: Factorial ARR - Compensation
  {
    id: "f-070",
    title: "Factorial ARR - Compensation",
    ownerId: "emp-006",
    assignee: { type: "area", name: "Compensation" },
    status: "on-track",
    measure: "9.825.191€",
    progress: 19,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-001",
    childrenIds: [],
    scope: "team",
  },

  // ── L1: Factorial ARR - Time
  {
    id: "f-080",
    title: "Factorial ARR - Time",
    ownerId: "emp-003",
    assignee: { type: "area", name: "Time" },
    status: "on-track",
    measure: "30.515.000€",
    progress: 20,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-001",
    childrenIds: [],
    scope: "team",
  },

  // ── L1: Factorial ARR - Marketing
  {
    id: "f-090",
    title: "Factorial ARR - Marketing",
    ownerId: "emp-011",
    assignee: { type: "area", name: "Marketing" },
    status: "on-track",
    measure: "-€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-001",
    childrenIds: [],
    scope: "team",
  },

  // ── L1: Factorial ARR - People
  {
    id: "f-100",
    title: "Factorial ARR - People",
    ownerId: "emp-002",
    assignee: { type: "department", departmentId: "dept-people" },
    status: "on-track",
    measure: "-€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-001",
    childrenIds: [],
    scope: "team",
  },

  // ── Standalone top-level: SLA
  {
    id: "f-110",
    title: "SLA",
    ownerId: "emp-001",
    assignee: { type: "company", name: "Factorial" },
    status: "on-track",
    measure: "100%",
    progress: 40,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: null,
    childrenIds: [
      "f-111",
      "f-112",
      "f-113",
      "f-114",
      "f-115",
      "f-116",
      "f-117",
      "f-118",
    ],
    scope: "team",
  },
  {
    id: "f-111",
    title: "SLA - Sales",
    ownerId: "emp-014",
    assignee: { type: "department", departmentId: "dept-sales" },
    status: "on-track",
    measure: "100%",
    progress: 55,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-110",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "f-112",
    title: "SLA - Product & Eng",
    ownerId: "emp-001",
    assignee: { type: "area", name: "Product & Eng" },
    status: "on-track",
    measure: "100%",
    progress: 38,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-110",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "f-113",
    title: "SLA - Talent",
    ownerId: "emp-002",
    assignee: { type: "area", name: "Talent" },
    status: "on-track",
    measure: "100%",
    progress: 42,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-110",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "f-114",
    title: "SLA - Finance",
    ownerId: "emp-010",
    assignee: { type: "area", name: "Finance" },
    status: "on-track",
    measure: "100%",
    progress: 30,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-110",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "f-115",
    title: "SLA - Compensation",
    ownerId: "emp-006",
    assignee: { type: "area", name: "Compensation" },
    status: "on-track",
    measure: "100%",
    progress: 35,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-110",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "f-116",
    title: "SLA - Time",
    ownerId: "emp-003",
    assignee: { type: "area", name: "Time" },
    status: "off-track",
    measure: "100%",
    progress: 22,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-110",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "f-117",
    title: "SLA - Marketing",
    ownerId: "emp-011",
    assignee: { type: "area", name: "Marketing" },
    status: "on-track",
    measure: "100%",
    progress: 50,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-110",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "f-118",
    title: "SLA - People",
    ownerId: "emp-002",
    assignee: { type: "department", departmentId: "dept-people" },
    status: "on-track",
    measure: "100%",
    progress: 45,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "f-110",
    childrenIds: [],
    scope: "team",
  },

  // ─── MY GOALS (Factorial) ──────────────────────────────────────────
  {
    id: "f-200",
    title: "Ship Goals v1",
    ownerId: "emp-001",
    assignee: { type: "individual", employeeId: "emp-001" },
    status: "on-track",
    measure: "0 → 1 release",
    progress: 70,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "f-201",
    title: "Deliver Q2 OKR presentation",
    ownerId: "emp-001",
    assignee: { type: "individual", employeeId: "emp-001" },
    status: "at-risk",
    measure: "0 → 1 deck",
    progress: 0,
    startDate: "2026-04-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
]

// ═══════════════════════════════════════════════════════════════════════
// LEFEBVRE fixtures — extracted from real Lefebvre production screenshot.
// Mix of company-level revenue goals, tech transformation goals, and
// departmental OKRs. Spanish goal titles preserved from the original.
// ═══════════════════════════════════════════════════════════════════════

const lefebvreGoals: GoalRecord[] = [
  // ─── TEAM GOALS ────────────────────────────────────────────────────
  {
    id: "lf-001",
    title: "Country revenue",
    ownerId: "emp-002",
    assignee: { type: "company", name: "Lefebvre" },
    status: "on-track",
    measure: "0€ → 52.700€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "team",
  },
  {
    id: "lf-002",
    title: "Country EBIT",
    ownerId: "emp-002",
    assignee: { type: "company", name: "Lefebvre" },
    status: "on-track",
    measure: "€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: null,
    childrenIds: [],
    scope: "team",
  },
  {
    id: "lf-003",
    title: "Country contribution to group net result",
    ownerId: "emp-002",
    assignee: { type: "company", name: "Lefebvre" },
    status: "partial",
    measure: "€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: null,
    childrenIds: [],
    scope: "team",
  },
  {
    id: "lf-010",
    title: "Acelerar la ejecución del roadmap de GenIA-L",
    ownerId: "emp-003",
    assignee: { type: "area", name: "Tecnología" },
    status: "on-track",
    measure: "100%",
    progress: 50,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "team",
  },
  {
    id: "lf-020",
    title: "Migración WEB a Cloud en un 75%",
    ownerId: "emp-003",
    assignee: { type: "area", name: "Tecnología" },
    status: "off-track",
    measure: "75%",
    progress: 25,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: null,
    childrenIds: ["lf-021", "lf-022"],
    scope: "team",
  },
  {
    id: "lf-021",
    title: "Migración de servicios legacy a Kubernetes",
    ownerId: "emp-003",
    assignee: { type: "area", name: "Tecnología" },
    status: "achieved",
    measure: "75%",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: "lf-020",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "lf-022",
    title: "Certificación ISO 27001 para entorno cloud",
    ownerId: "emp-016",
    assignee: { type: "area", name: "Tecnología" },
    status: "on-track",
    measure: "1 certificación",
    progress: 60,
    startDate: "2026-03-01",
    dueDate: "2026-12-31",
    parentId: "lf-020",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "lf-030",
    title: "Integración IA en Procesos internos",
    ownerId: "emp-003",
    assignee: { type: "area", name: "Tecnología" },
    status: "achieved",
    measure: "100%",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "team",
  },
  {
    id: "lf-040",
    title: "Resultado neto del grupo 10.702k€",
    ownerId: "emp-010",
    assignee: { type: "group", employeeIds: ["emp-010", "emp-011", "emp-012"] },
    status: "achieved",
    measure: "0€ → 10.702€",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: ["lf-041", "lf-042"],
    scope: "team",
  },
  {
    id: "lf-041",
    title: "Optimizar estructura de costes del grupo",
    ownerId: "emp-010",
    assignee: { type: "area", name: "Finance" },
    status: "on-track",
    measure: "5% reducción",
    progress: 40,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: "lf-040",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "lf-042",
    title: "Cerrar M&A pipeline Q1",
    ownerId: "emp-011",
    assignee: { type: "area", name: "Finance" },
    status: "achieved",
    measure: "2 deals",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "lf-040",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "lf-050",
    title: "Identificar, documentar y diseñar 5 casos de uso clave del Ecosistema",
    ownerId: "emp-004",
    assignee: { type: "individual", employeeId: "emp-004" },
    status: "off-track",
    measure: "5",
    progress: 10,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "team",
  },
  {
    id: "lf-060",
    title: "Contribuir al desarrollo de una comunicación clara y consistente",
    ownerId: "emp-005",
    assignee: { type: "area", name: "Comunicación" },
    status: "achieved",
    measure: "100%",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "team",
  },
  {
    id: "lf-070",
    title: "Eficiencias en procesos internos (IA y no IA) de cada Dpto.",
    ownerId: "emp-006",
    assignee: { type: "area", name: "Editorial" },
    status: "achieved",
    measure: "100%",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "team",
  },
  {
    id: "lf-080",
    title: "Mejora en experiencia de cliente, entre los productos del Ecosistema",
    ownerId: "emp-007",
    assignee: { type: "individual", employeeId: "emp-007" },
    status: "achieved",
    measure: "100%",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "team",
  },
  {
    id: "lf-090",
    title: "Evolucionar el proyecto Next en un 40%",
    ownerId: "emp-004",
    assignee: { type: "individual", employeeId: "emp-004" },
    status: "achieved",
    measure: "100%",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "team",
  },
  {
    id: "lf-100",
    title: "Nueva Organización Orientada al producto (NEXT)",
    ownerId: "emp-003",
    assignee: { type: "area", name: "Tecnología" },
    status: "achieved",
    measure: "100%",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: ["lf-101"],
    scope: "team",
  },
  {
    id: "lf-101",
    title: "Definir squads y ownership de producto",
    ownerId: "emp-003",
    assignee: { type: "area", name: "Tecnología" },
    status: "achieved",
    measure: "100%",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "lf-100",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "lf-110",
    title: "Lograr 800 k€ en ingresos por ventas de bases de datos online",
    ownerId: "emp-008",
    assignee: { type: "individual", employeeId: "emp-008" },
    status: "achieved",
    measure: "0€ → 800.000€",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "team",
  },
  {
    id: "lf-120",
    title: "Implantar al menos 2 eficiencias de IA Gen",
    ownerId: "emp-003",
    assignee: { type: "area", name: "Tecnología" },
    status: "achieved",
    measure: "100%",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: ["lf-121", "lf-122"],
    scope: "team",
  },
  {
    id: "lf-121",
    title: "Despliegue de copiloto legal para clientes",
    ownerId: "emp-003",
    assignee: { type: "area", name: "Tecnología" },
    status: "achieved",
    measure: "1 release",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "lf-120",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "lf-122",
    title: "Automatización de resúmenes jurisprudenciales",
    ownerId: "emp-003",
    assignee: { type: "area", name: "Tecnología" },
    status: "achieved",
    measure: "1 pipeline",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: "lf-120",
    childrenIds: [],
    scope: "team",
  },

  // ─── MY GOALS (Lefebvre) ──────────────────────────────────────────
  {
    id: "lf-200",
    title: "Completar certificación en derecho digital",
    ownerId: "emp-001",
    assignee: { type: "individual", employeeId: "emp-001" },
    status: "on-track",
    measure: "0 → 1 cert",
    progress: 40,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "lf-201",
    title: "Liderar migración del módulo fiscal",
    ownerId: "emp-001",
    assignee: { type: "team", teamId: "team-platform" },
    status: "on-track",
    measure: "0% → 100%",
    progress: 65,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "lf-202",
    title: "Reducir incidencias críticas en plataforma editorial",
    ownerId: "emp-001",
    assignee: { type: "individual", employeeId: "emp-001" },
    status: "achieved",
    measure: "20 → 5 incidencias",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
]

// ═══════════════════════════════════════════════════════════════════════
// GOFIT fixtures — fitness/gym chain company. Mix of financial KPIs,
// operational excellence, and expansion goals.
// ═══════════════════════════════════════════════════════════════════════

const gofitGoals: GoalRecord[] = [
  // ─── TEAM GOALS ────────────────────────────────────────────────────
  {
    id: "gf-001",
    title: "EBITDA GENERAL",
    ownerId: "emp-002",
    assignee: { type: "company", name: "GOfit" },
    status: "on-track",
    measure: "0€ → 52.700€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "team",
  },
  {
    id: "gf-010",
    title: "NPS GENERAL",
    ownerId: "emp-002",
    assignee: { type: "company", name: "GOfit" },
    status: "on-track",
    measure: "0€ → 52.700€",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: ["gf-011", "gf-012", "gf-013", "gf-014", "gf-015"],
    scope: "team",
  },
  {
    id: "gf-011",
    title: "NPS Centro 1",
    ownerId: "emp-003",
    assignee: { type: "area", name: "Centro 1" },
    status: "on-track",
    measure: "10 NPS",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "gf-010",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "gf-012",
    title: "NPS Centro 2",
    ownerId: "emp-004",
    assignee: { type: "area", name: "Centro 2" },
    status: "on-track",
    measure: "10 NPS",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "gf-010",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "gf-013",
    title: "NPS Centro 3",
    ownerId: "emp-005",
    assignee: { type: "area", name: "Centro 3" },
    status: "on-track",
    measure: "10 NPS",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "gf-010",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "gf-014",
    title: "NPS Centro 4",
    ownerId: "emp-006",
    assignee: { type: "area", name: "Centro 4" },
    status: "on-track",
    measure: "10 NPS",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "gf-010",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "gf-015",
    title: "NPS Centro 5",
    ownerId: "emp-007",
    assignee: { type: "area", name: "Centro 5" },
    status: "on-track",
    measure: "10 NPS",
    progress: 17,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "gf-010",
    childrenIds: [],
    scope: "team",
  },

  // ─── MY GOALS (GOfit) ─────────────────────────────────────────────
  {
    id: "gf-200",
    title: "Certificación entrenador personal nivel 3",
    ownerId: "emp-001",
    assignee: { type: "individual", employeeId: "emp-001" },
    status: "on-track",
    measure: "0 → 1 cert",
    progress: 50,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "gf-201",
    title: "Implementar dashboard de KPIs operativos",
    ownerId: "emp-001",
    assignee: { type: "team", teamId: "team-platform" },
    status: "on-track",
    measure: "0 → 1 dashboard",
    progress: 75,
    startDate: "2026-01-01",
    dueDate: "2026-04-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "gf-202",
    title: "Reducir tiempo medio de onboarding de socio",
    ownerId: "emp-001",
    assignee: { type: "individual", employeeId: "emp-001" },
    status: "achieved",
    measure: "15min → 5min",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-03-31",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
]

// ═══════════════════════════════════════════════════════════════════════
// PLEXUS fixtures — tech consulting / training company. Heavy on
// training completion goals grouped under "Objetivos formativos" and
// "Otros objetivos". Extracted from production screenshot.
// ═══════════════════════════════════════════════════════════════════════

const plexusGoals: GoalRecord[] = [
  // ─── TEAM GOALS ────────────────────────────────────────────────────

  // Root: Objetivos formativos 2026
  {
    id: "px-001",
    title: "Objetivos formativos 2026",
    ownerId: "emp-002",
    assignee: { type: "company", name: "Plexus" },
    status: "on-track",
    measure: "Based on subgoals",
    progress: 18,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: null,
    childrenIds: [
      "px-010",
      "px-011",
      "px-012",
      "px-013",
      "px-014",
      "px-015",
      "px-016",
      "px-017",
      "px-018",
    ],
    scope: "team",
  },
  {
    id: "px-010",
    title: "Formación metodologías ágiles",
    ownerId: "emp-003",
    assignee: { type: "individual", employeeId: "emp-003" },
    status: "achieved",
    measure: "Training completion",
    progress: 100,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "px-001",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "px-011",
    title: "Formación en inglés",
    ownerId: "emp-003",
    assignee: { type: "individual", employeeId: "emp-003" },
    status: "on-track",
    measure: "Training completion",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "px-001",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "px-012",
    title: "Formación en inglés",
    ownerId: "emp-004",
    assignee: { type: "individual", employeeId: "emp-004" },
    status: "on-track",
    measure: "Training completion",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "px-001",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "px-013",
    title: "Formación metodologías ágiles",
    ownerId: "emp-004",
    assignee: { type: "individual", employeeId: "emp-004" },
    status: "on-track",
    measure: "Training completion",
    progress: 20,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "px-001",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "px-014",
    title: "Formación metodologías ágiles",
    ownerId: "emp-005",
    assignee: { type: "individual", employeeId: "emp-005" },
    status: "on-track",
    measure: "Training completion",
    progress: 40,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "px-001",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "px-015",
    title: "Formación en scrum",
    ownerId: "emp-004",
    assignee: { type: "individual", employeeId: "emp-004" },
    status: "at-risk",
    measure: "Training completion",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "px-001",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "px-016",
    title: "Formación en excel",
    ownerId: "emp-004",
    assignee: { type: "individual", employeeId: "emp-004" },
    status: "on-track",
    measure: "Training completion",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "px-001",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "px-017",
    title: "Formación en inglés",
    ownerId: "emp-003",
    assignee: { type: "individual", employeeId: "emp-003" },
    status: "missed",
    measure: "Training completion",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "px-001",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "px-018",
    title: "Formación en agile",
    ownerId: "emp-003",
    assignee: { type: "individual", employeeId: "emp-003" },
    status: "partial",
    measure: "Training completion",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "px-001",
    childrenIds: [],
    scope: "team",
  },

  // Root: Otros objetivos
  {
    id: "px-050",
    title: "Otros objetivos",
    ownerId: "emp-002",
    assignee: { type: "company", name: "Plexus" },
    status: "on-track",
    measure: "Based on subgoals",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: null,
    childrenIds: ["px-051", "px-052", "px-053", "px-054"],
    scope: "team",
  },
  {
    id: "px-051",
    title: "Reuniones semanales",
    ownerId: "emp-003",
    assignee: { type: "individual", employeeId: "emp-003" },
    status: "on-track",
    measure: "Training completion",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "px-050",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "px-052",
    title: "Reuniones trimestrales",
    ownerId: "emp-004",
    assignee: { type: "individual", employeeId: "emp-004" },
    status: "on-track",
    measure: "Training completion",
    progress: 0,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "px-050",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "px-053",
    title: "Certificación ISO 9001",
    ownerId: "emp-006",
    assignee: { type: "area", name: "Calidad" },
    status: "on-track",
    measure: "1 certificación",
    progress: 35,
    startDate: "2026-01-01",
    dueDate: "2026-09-30",
    parentId: "px-050",
    childrenIds: [],
    scope: "team",
  },
  {
    id: "px-054",
    title: "Mejorar satisfacción cliente a 4.5/5",
    ownerId: "emp-007",
    assignee: { type: "area", name: "Delivery" },
    status: "on-track",
    measure: "4.1 → 4.5",
    progress: 25,
    startDate: "2026-01-01",
    dueDate: "2026-12-31",
    parentId: "px-050",
    childrenIds: [],
    scope: "team",
  },

  // ─── MY GOALS (Plexus) ────────────────────────────────────────────
  {
    id: "px-200",
    title: "Completar certificación Scrum Master",
    ownerId: "emp-001",
    assignee: { type: "individual", employeeId: "emp-001" },
    status: "on-track",
    measure: "0 → 1 cert",
    progress: 60,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
  {
    id: "px-201",
    title: "Liderar 3 workshops de transformación digital",
    ownerId: "emp-001",
    assignee: { type: "individual", employeeId: "emp-001" },
    status: "on-track",
    measure: "0 → 3 workshops",
    progress: 33,
    startDate: "2026-01-01",
    dueDate: "2026-06-30",
    parentId: null,
    childrenIds: [],
    scope: "mine",
  },
]

// ═══════════════════════════════════════════════════════════════════════
// Public API — company-aware wrappers around the raw fixture arrays
// ═══════════════════════════════════════════════════════════════════════

function fixturesForCompany(companyId: CompanyId): GoalRecord[] {
  switch (companyId) {
    case "factorial":
      return factorialGoals
    case "lefebvre":
      return lefebvreGoals
    case "gofit":
      return gofitGoals
    case "plexus":
      return plexusGoals
    case "default":
    default:
      return defaultGoals
  }
}

/** Kept for backwards-compat with detail page / activity references. */
export const goalsFixtures: GoalRecord[] = [
  ...defaultGoals,
  ...factorialGoals,
  ...lefebvreGoals,
  ...gofitGoals,
  ...plexusGoals,
]

/** Get goals for a given scope (top-level only) within a company. */
export function getGoalsByScope(
  scope: "team" | "all" | "mine",
  companyId: CompanyId = "default"
): GoalRecord[] {
  const goals = fixturesForCompany(companyId)
  if (scope === "all") {
    return goals.filter((g) => g.parentId === null)
  }
  return goals.filter((g) => g.parentId === null && g.scope === scope)
}

/** Get children for a given goal id (searches across all companies). */
export function getGoalChildren(parentId: string): GoalRecord[] {
  return goalsFixtures.filter((g) => g.parentId === parentId)
}

/** Count goals per scope (top-level only) within a company. */
export function getGoalCounts(companyId: CompanyId = "default") {
  const goals = fixturesForCompany(companyId)
  const all = goals.filter((g) => g.parentId === null)
  const team = all.filter((g) => g.scope === "team")
  const mine = all.filter((g) => g.scope === "mine")
  return { team: team.length, all: all.length, mine: mine.length }
}
