export declare const wizardRootVariants: import("node_modules/tailwind-variants/dist").TVReturnType<{} | {} | {}, undefined, "flex-1", {} | {}, undefined, import("node_modules/tailwind-variants/dist").TVReturnType<unknown, undefined, "flex-1", unknown, unknown, undefined>>;
export declare const wizardHeaderVariants: import("node_modules/tailwind-variants/dist").TVReturnType<{} | {} | {}, undefined, "gap-3 px-4 pt-4 pb-2", {} | {}, undefined, import("node_modules/tailwind-variants/dist").TVReturnType<unknown, undefined, "gap-3 px-4 pt-4 pb-2", unknown, unknown, undefined>>;
export declare const wizardTitleBlockVariants: import("node_modules/tailwind-variants/dist").TVReturnType<{} | {} | {}, undefined, "pt-1", {} | {}, undefined, import("node_modules/tailwind-variants/dist").TVReturnType<unknown, undefined, "pt-1", unknown, unknown, undefined>>;
export declare const wizardContentVariants: import("node_modules/tailwind-variants/dist").TVReturnType<{} | {} | {}, undefined, "flex-1", {} | {}, undefined, import("node_modules/tailwind-variants/dist").TVReturnType<unknown, undefined, "flex-1", unknown, unknown, undefined>>;
export declare const wizardFooterVariants: import("node_modules/tailwind-variants/dist").TVReturnType<{} | {} | {}, undefined, "flex-row gap-3 px-4 pt-3 pb-4", {} | {}, undefined, import("node_modules/tailwind-variants/dist").TVReturnType<unknown, undefined, "flex-row gap-3 px-4 pt-3 pb-4", unknown, unknown, undefined>>;
export declare const wizardFooterButtonVariants: import("node_modules/tailwind-variants/dist").TVReturnType<{} | {} | {}, undefined, "flex-1 flex-row", {} | {}, undefined, import("node_modules/tailwind-variants/dist").TVReturnType<unknown, undefined, "flex-1 flex-row", unknown, unknown, undefined>>;
export declare const wizardScrollContentStyle: {
    padding: number;
};
//# sourceMappingURL=F0Wizard.styles.d.ts.map