import { F0Alert, F0Button, F0Card, F0Heading, F0Text } from "@factorialco/f0-react"
import { Check, Cross } from "@factorialco/f0-react/icons/app"

import { draftCourses, recommendations } from "../fixtures"

const statusLabel: Record<string, string> = {
  pending: "Pending review",
  approved: "Approved",
  rejected: "Rejected",
}

const statusColor: Record<string, string> = {
  pending: "bg-f1-background-warning text-f1-foreground-warning",
  approved: "bg-f1-background-positive text-f1-foreground-positive",
  rejected: "bg-f1-background-critical text-f1-foreground-critical",
}

export function DraftCoursesTab() {
  const pendingCount = draftCourses.filter((d) => d.status === "pending").length

  return (
    <div className="flex flex-col gap-6">
      <header className="flex items-center justify-between">
        <div className="flex flex-col gap-1">
          <F0Heading content="Draft courses" variant="heading-large" as="h1" />
          <F0Text
            content="New courses generated by the AI Mentor that require L&D approval before being assigned to employees."
            variant="body"
          />
        </div>
      </header>

      {pendingCount > 0 && (
        <F0Alert
          variant="info"
          title={`${pendingCount} course${pendingCount > 1 ? "s" : ""} awaiting your review`}
          description="Review each draft carefully. Approved courses will be assigned to the employee automatically. Rejected courses will not be assigned and the employee will not receive a recommendation this cycle."
        />
      )}

      <div className="flex flex-col gap-4">
        {draftCourses.map((draft) => {
          const rec = recommendations.find((r) => r.id === draft.recommendationId)

          return (
            <F0Card key={draft.id} title={draft.title}>
              <div className="flex flex-col gap-4 p-4">
                {/* Meta row */}
                <div className="flex flex-wrap items-center gap-2">
                  <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${statusColor[draft.status]}`}>
                    {statusLabel[draft.status]}
                  </span>
                  <span className="inline-flex items-center rounded-full bg-f1-background-secondary px-2 py-0.5 text-xs text-f1-foreground-secondary">
                    {draft.learnerRole} · {draft.learnerLevel}
                  </span>
                  <span className="inline-flex items-center rounded-full bg-f1-background-secondary px-2 py-0.5 text-xs text-f1-foreground-secondary">
                    {draft.estimatedDurationMin} min
                  </span>
                  <span className="inline-flex items-center rounded-full bg-f1-background-info px-2 py-0.5 text-xs text-f1-foreground-info">
                    Competency: {draft.targetCompetency}
                  </span>
                </div>

                {/* Gap context */}
                <div className="flex flex-col gap-1">
                  <F0Text content="Gap context" variant="label" />
                  <F0Text content={draft.gapContext} variant="small" />
                </div>

                {/* Proposed modules */}
                <div className="flex flex-col gap-2">
                  <F0Text content="Proposed modules" variant="label" />
                  <div className="flex flex-col gap-1">
                    {draft.proposedModules.map((mod, i) => (
                      <div key={i} className="flex items-start gap-2">
                        <span className="mt-0.5 h-4 w-4 shrink-0 rounded-full bg-f1-background-secondary text-center text-xs leading-4 text-f1-foreground-secondary">
                          {i + 1}
                        </span>
                        <F0Text content={mod} variant="small" />
                      </div>
                    ))}
                  </div>
                </div>

                {/* Employee this is for */}
                {rec && (
                  <div className="rounded border border-f1-border bg-f1-background-secondary p-3">
                    <F0Text content="This course will be assigned to:" variant="label" />
                    <F0Text content={`Employee ID: ${rec.employeeId} · ${rec.gapSummary}`} variant="small" />
                  </div>
                )}

                {/* Actions */}
                {draft.status === "pending" && (
                  <div className="flex items-center gap-2 pt-2">
                    <F0Button
                      label="Approve and assign"
                      variant="default"
                      icon={Check}
                      onClick={() => {}}
                    />
                    <F0Button
                      label="Reject"
                      variant="outline"
                      icon={Cross}
                      onClick={() => {}}
                    />
                    <F0Button
                      label="Edit before approving"
                      variant="outline"
                      onClick={() => {}}
                    />
                  </div>
                )}
              </div>
            </F0Card>
          )
        })}
      </div>
    </div>
  )
}
