name: 'Setup Node and pnpm'
description: 'Setup Node.js and pnpm, install dependencies and build'
inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '22.x'
  registry:
    description: 'Registry URL'
    required: false
    default: 'https://registry.npmjs.org/'
  scope:
    description: 'Scope'
    required: false
    default: '@factorialco'

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry }}
        scope: ${{ inputs.scope }}
        cache: pnpm

    - name: Install dependencies
      run: pnpm install
      shell: bash
