import { StoryFn, StoryObj } from "@storybook/react-vite"
import { expect, within } from "storybook/test"
import { CheckDouble, ExternalLink } from "@/icons/app"
import { WithDataTestIdProps } from "@/lib/data-testid"
import { AiBannerSkeleton } from "./AiBannerInternal"
import { F0AiBanner, F0AiBannerProps } from "."

const meta = {
  title: "AI/AiBanner",
  component: F0AiBanner,
  // The tag is what the sidebar badge and the component-status API read. No
  // "(deprecated)" title suffix: that changes the page id and 404s every
  // existing link, and marks nothing the tag does not already mark.
  tags: ["deprecated"],
  parameters: {
    layout: "centered",
    docs: {
      description: {
        component: [
          "**Deprecated — use `F0AiCallout`.**",
          "",
          "This one has no status, so it cannot say how much a message matters, and it signals its",
          "authorship with a gradient built from raw hex — two signals for one message, and one that",
          "cannot follow a theme. Both of its actions are outlined, which reads as two peers where",
          "there is a recommendation and a way out of it.",
          "",
          'Migration: `content` becomes `children` (nodes, not a string), add `status="neutral"` with',
          "an `icon` describing the content, and `primaryAction` becomes `action`. The byline is not a",
          "prop — every F0AiCallout renders it.",
        ].join("\n"),
      },
    },
  },
  argTypes: {
    title: {
      control: "text",
      description: "The title displayed in the banner header",
    },
    onClose: {
      control: false,
      description: "Callback when the close button is clicked",
    },
    primaryAction: {
      control: "object",
      description: "Primary action button configuration",
    },
    secondaryAction: {
      control: "object",
      description: "Secondary action button configuration",
    },
    content: {
      control: "text",
      description: "Html or plain text content displayed in the banner body",
    },
  },
  decorators: [
    (Story: StoryFn) => (
      <div className="w-96">
        <Story />
      </div>
    ),
  ],
}

export const Default: StoryObj<F0AiBannerProps> = {
  args: {
    title: "Approval suggested",
    onClose: () => alert("Banner closed"),
    primaryAction: {
      label: "Approve request",
      onClick: () => alert("Primary action clicked"),
      icon: CheckDouble,
    },
    secondaryAction: {
      label: "Set up smart rule",
      onClick: () => alert("Secondary action clicked"),
      icon: ExternalLink,
    },
    content: `<div>
        <p>
          Based on Elias&apos;s <u>team availability</u>, <u>time off policy</u>
          and <u>schedule</u> this request looks good to approve.
        </p>
        <p>If you approve, Elias will have 2 holiday days remaining.</p>
      </div>`,
  },
}

export const WithoutActions: StoryObj<F0AiBannerProps> = {
  args: {
    title: "Information",
    onClose: () => alert("Banner closed"),
    content:
      "This is a simple informational banner without any action buttons. It&apos;s useful for displaying important messages or updates generated by AI.",
  },
}

export const Skeleton: StoryObj = {
  render: () => <AiBannerSkeleton />,
}

export const SkeletonCompact: StoryObj = {
  render: () => <AiBannerSkeleton compact />,
}

export const WithDataTestId: StoryObj<F0AiBannerProps & WithDataTestIdProps> = {
  args: {
    ...Default.args,
    dataTestId: "ai-banner-test-id",
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement)
    await expect(canvas.getByTestId("ai-banner-test-id")).toBeInTheDocument()
  },
}

export default meta
