import type { F0MapProvider } from "../providers/names"
import darkStyle from "./f0-dark.json"
import lightStyle from "./f0-light.json"
import googleDarkStyle from "./google-dark.json"
import googleLightStyle from "./google-light.json"

/**
 * A light/dark style pair for one engine. `light` and `dark` are deliberately
 * opaque - their real shape belongs to the engine (a MapLibre
 * `StyleSpecification` or a style URL today), and F0Map's public surface must
 * never make a consumer import an engine's types to describe a style.
 */
export interface F0MapStyle {
  provider: F0MapProvider
  light: unknown
  dark: unknown
}

/**
 * f0-themed MapLibre styles over keyless OpenFreeMap vector tiles.
 *
 * Generated by `styles/buildStyles.mjs` from the OpenFreeMap Bright style: every
 * layer color is remapped to the nearest f0 token (CIEDE2000) and muted, then
 * resolved to concrete hex for the light and dark neutral ramps. Regenerate with
 * `node src/patterns/F0Map/styles/buildStyles.mjs`.
 */
export const f0MapStyles: F0MapStyle = {
  provider: "maplibre",
  light: lightStyle,
  dark: darkStyle,
}

/**
 * The same f0 tokens in Google's styling model, which is far coarser: no
 * per-layer control, no zoom-dependent or data-driven stylers, and no way to
 * add a layer its basemap omits. 14 of the flavor's 25 cartographic roles have
 * an expression; the rest keep Google's own colours. The two maps do not match,
 * and both track the tokens.
 */
export const googleMapStyles: F0MapStyle = {
  provider: "google",
  light: googleLightStyle,
  dark: googleDarkStyle,
}

/** The look an engine gets when the consumer names no style. */
export const defaultMapStyle = (provider: F0MapProvider): F0MapStyle =>
  provider === "google" ? googleMapStyles : f0MapStyles

export type { F0MapProvider }
