import darkStyle from "./f0-dark.json"
import lightStyle from "./f0-light.json"

/**
 * Which rendering engine a style is written for. The tag exists so a style
 * built for one engine can never be handed to another: the shapes are not
 * interchangeable, and without it the mismatch would only surface at runtime.
 */
export type F0MapProvider = "maplibre"

/**
 * A light/dark style pair for one engine. `light` and `dark` are deliberately
 * opaque - their real shape belongs to the engine (a MapLibre
 * `StyleSpecification` or a style URL today), and F0Map's public surface must
 * never make a consumer import an engine's types to describe a style.
 */
export interface F0MapStyle {
  provider: F0MapProvider
  light: unknown
  dark: unknown
}

/**
 * f0-themed MapLibre styles over keyless OpenFreeMap vector tiles.
 *
 * Generated by `styles/buildStyles.mjs` from the OpenFreeMap Bright style: every
 * layer color is remapped to the nearest f0 token (CIEDE2000) and muted, then
 * resolved to concrete hex for the light and dark neutral ramps. Regenerate with
 * `node src/patterns/F0Map/styles/buildStyles.mjs`.
 */
export const f0MapStyles: F0MapStyle = {
  provider: "maplibre",
  light: lightStyle,
  dark: darkStyle,
}
