import { IconType } from "@/components/F0Icon"

/**
 * Inline dataset for client-side file generation (Excel / CSV / TSV / JSON / PDF).
 * Sent by the agent with the raw query results.
 */
export type F0DataDownloadDataset = {
  /**
   * Column headers in display order.
   */
  columns: string[]
  /**
   * Array of row objects keyed by column name.
   */
  rows: Record<string, unknown>[]
  /**
   * Total number of rows returned by the query (before truncation).
   * Used together with previewCount to render the preview note.
   */
  totalCount?: number
  /**
   * Number of rows shown in the markdown preview table.
   * Used together with totalCount to render the preview note.
   */
  previewCount?: number
  /**
   * Map of raw column names to human-readable labels in the user's language.
   * Used for Excel/CSV headers. Falls back to the raw column name when absent.
   */
  columnLabels?: Record<string, string>
}

/**
 * Props for the F0DataDownload component.
 *
 * Renders an optional markdown preview/description followed by
 * "Download Excel" and other format buttons (CSV, TSV, JSON, PDF).
 * The component generates the files client-side from the provided dataset.
 */
export type F0DataDownloadProps = {
  /**
   * Optional markdown content to display above the download buttons.
   * Typically a 5-row preview table generated by the agent.
   */
  markdown?: string
  /**
   * Descriptive filename (without extension) for the downloaded files.
   * Generated by the AI to reflect the query content in the user's language.
   */
  filename?: string
  /**
   * Raw dataset for client-side Excel and CSV generation.
   */
  dataset: F0DataDownloadDataset
}

/**
 * Definition for a download format.
 *
 * To add a new format, create a file in this folder that exports a
 * `DownloadFormatDefinition` and register it in `./index.ts`.
 */
export type DownloadFormatDefinition = {
  /** Unique key used as the button value (e.g. "excel", "csv"). */
  key: string
  /** Short format name used for i18n interpolation (e.g. "Excel", "CSV"). */
  formatName: string
  /** Icon component rendered next to the label. */
  icon: IconType
  /** Generate the file and trigger a browser download. */
  handler: (dataset: F0DataDownloadDataset, filename: string) => void
}
