/**
 * Inline dataset for client-side file generation (Excel / CSV).
 * Sent by the agent with the raw query results.
 */
export type F0DataDownloadDataset = {
  /**
   * Column headers in display order.
   */
  columns: string[]
  /**
   * Array of row objects keyed by column name.
   */
  rows: Record<string, unknown>[]
  /**
   * Total number of rows returned by the query (before truncation).
   * Used together with previewCount to render the preview note.
   */
  totalCount?: number
  /**
   * Number of rows shown in the markdown preview table.
   * Used together with totalCount to render the preview note.
   */
  previewCount?: number
  /**
   * Map of raw column names to human-readable labels in the user's language.
   * Used for Excel/CSV headers. Falls back to the raw column name when absent.
   */
  columnLabels?: Record<string, string>
}

/**
 * Props for the F0DataDownload component.
 *
 * Renders an optional markdown preview/description followed by
 * "Download Excel" and "Download CSV" buttons. The component generates
 * the files client-side from the provided dataset.
 */
export type F0DataDownloadProps = {
  /**
   * Optional markdown content to display above the download buttons.
   * Typically a 5-row preview table generated by the agent.
   */
  markdown?: string
  /**
   * Descriptive filename (without extension) for the downloaded files.
   * Generated by the AI to reflect the query content in the user's language.
   */
  filename?: string
  /**
   * Raw dataset for client-side Excel and CSV generation.
   */
  dataset: F0DataDownloadDataset
}
