import { F0Alert, F0Button, F0Card, F0Heading, F0Text } from "@factorialco/f0-react"
import { Add, Pencil, Sparkles } from "@factorialco/f0-react/icons/app"

import { careerPaths, competencies } from "../fixtures"

const levelColor: Record<string, string> = {
  basic: "bg-f1-background-secondary text-f1-foreground-secondary",
  intermediate: "bg-f1-background-info text-f1-foreground-info",
  advanced: "bg-f1-background-positive text-f1-foreground-positive",
  expert: "bg-f1-background-warning text-f1-foreground-warning",
}

export function CareerPathsTab() {
  return (
    <div className="flex flex-col gap-6">
      <header className="flex items-center justify-between">
        <div className="flex flex-col gap-1">
          <F0Heading content="Career paths" variant="heading-large" as="h1" />
          <F0Text
            content="Define progression levels and required competencies per role. The AI Mentor uses these to recommend growth-oriented courses, not just gap-fixing ones."
            variant="body"
          />
        </div>
        <div className="flex items-center gap-2">
          <F0Button label="New career path" variant="default" icon={Add} onClick={() => {}} />
        </div>
      </header>

      <F0Alert
        variant="info"
        title="Career paths are optional but expand AI Mentor capabilities"
        description="Without a career path, the AI Mentor only fixes current gaps. With a career path configured, it also recommends what employees need to learn to reach their next level."
      />

      <div className="flex flex-col gap-4">
        {careerPaths.map((cp) => (
          <F0Card
            key={cp.id}
            title={cp.roleName}
            description={`${cp.department} · ${cp.levels.length} levels · Last updated ${cp.lastUpdated}`}
          >
            <div className="flex flex-col gap-4 p-4">
              {/* AI generated badge */}
              {cp.isAiGenerated && (
                <div className="flex items-center gap-2">
                  <Sparkles className="h-4 w-4 text-f1-foreground-info" />
                  <F0Text
                    content="Generated by AI from role name and company context. Review and adjust to match your expectations."
                    variant="small"
                  />
                </div>
              )}

              {/* Levels */}
              <div className="flex gap-3 overflow-x-auto pb-1">
                {cp.levels.map((lvl) => (
                  <div
                    key={lvl.id}
                    className="flex min-w-[160px] flex-col gap-2 rounded border border-f1-border bg-f1-background-secondary p-3"
                  >
                    <div className="flex items-center gap-1">
                      <span className="text-xs font-semibold text-f1-foreground-secondary">
                        L{lvl.order}
                      </span>
                      <F0Text content={lvl.label} variant="label" />
                    </div>
                    <div className="flex flex-col gap-1">
                      {lvl.requirements.map((req) => {
                        const comp = competencies.find((c) => c.id === req.competencyId)
                        return (
                          <div key={req.competencyId} className="flex items-center justify-between gap-1">
                            <F0Text content={comp?.name ?? req.competencyId} variant="small" />
                            <span className={`inline-flex shrink-0 items-center rounded px-1.5 py-0.5 text-[10px] font-medium ${levelColor[req.level]}`}>
                              {req.level}
                            </span>
                          </div>
                        )
                      })}
                    </div>
                  </div>
                ))}
              </div>

              {/* Actions */}
              <div className="flex items-center gap-2">
                <F0Button label="Edit" variant="outline" icon={Pencil} onClick={() => {}} />
              </div>
            </div>
          </F0Card>
        ))}
      </div>
    </div>
  )
}
