import type { StrategyGoal } from "./types"

export const strategyGoals: StrategyGoal[] = [
  // ── Top-level company goal ───────────────────────────────────────────

  {
    id: "sg-000",
    title: "Factorial ARR",
    description: "Overall annual recurring revenue target for Factorial.",
    level: "company",
    status: "in-progress",
    progress: 47,
    ownerId: "emp-010",
    contributorIds: ["emp-001", "emp-002", "emp-004", "emp-008", "emp-014"],
    parentId: null,
    dueDate: "2026-06-30",
    assignation: "Factorial",
    measureStart: 120000,
    measureTarget: 200000,
    measureCurrent: 158500,
  },

  // ── Company-level sub-goals ──────────────────────────────────────────

  {
    id: "sg-001",
    title: "Factorial ARR - Product target",
    description: "Achieve the annual recurring revenue target across all product domains.",
    level: "company",
    status: "in-progress",
    progress: 45,
    ownerId: "emp-010",
    contributorIds: ["emp-001", "emp-002", "emp-004", "emp-008", "emp-014"],
    parentId: "sg-000",
    dueDate: "2026-06-30",
    assignation: "Factorial",
    measureStart: 80000,
    measureTarget: 120000,
    measureCurrent: 98000,
  },
  {
    id: "sg-014",
    title: "Factorial ARR – Sales target",
    description: "Drive new business ARR through the sales organization.",
    level: "company",
    status: "on-track",
    progress: 55,
    ownerId: "emp-010",
    contributorIds: [],
    parentId: "sg-000",
    dueDate: "2026-05-31",
    assignation: "Sales team",
    measureStart: 30000,
    measureTarget: 60000,
    measureCurrent: 46500,
  },
  {
    id: "sg-015",
    title: "Factorial ARR – CX target",
    description: "Grow ARR through upsell, cross-sell and retention in the CX organization.",
    level: "company",
    status: "in-progress",
    progress: 40,
    ownerId: "emp-010",
    contributorIds: [],
    parentId: "sg-000",
    dueDate: "2026-06-15",
    assignation: "CX team",
    measureStart: 10000,
    measureTarget: 20000,
    measureCurrent: 14000,
  },

  // ── Team-level: Product domain ARR goals ─────────────────────────────

  {
    id: "sg-002",
    title: "Talent Domain ARR",
    description: "Drive ARR growth in the Talent product domain (Performance, Recruitment, Training).",
    level: "team",
    status: "on-track",
    progress: 60,
    ownerId: "emp-001",
    contributorIds: ["emp-003", "emp-007"],
    parentId: "sg-001",
    dueDate: "2026-06-20",
    assignation: "Talent",
    measureStart: 15000,
    measureTarget: 25000,
    measureCurrent: 21000,
  },
  {
    id: "sg-003",
    title: "Finance Domain ARR",
    description: "Drive ARR growth in the Finance product domain (Payroll, Expenses, Compensation).",
    level: "team",
    status: "at-risk",
    progress: 30,
    ownerId: "emp-004",
    contributorIds: ["emp-005", "emp-006"],
    parentId: "sg-001",
    dueDate: "2026-05-15",
    assignation: "Finance Domain",
    measureStart: 20000,
    measureTarget: 32000,
    measureCurrent: 23600,
  },
  {
    id: "sg-004",
    title: "Operation Domain ARR",
    description: "Drive ARR growth in the Operations domain (Time Off, Shifts, Clock-in).",
    level: "team",
    status: "in-progress",
    progress: 50,
    ownerId: "emp-008",
    contributorIds: ["emp-009"],
    parentId: "sg-001",
    dueDate: "2026-04-30",
    assignation: "Operations Domain",
    measureStart: 12000,
    measureTarget: 18000,
    measureCurrent: 15000,
  },
  {
    id: "sg-005",
    title: "IT Domain ARR",
    description: "Drive ARR growth in the IT domain (Assets, Software, Provisioning).",
    level: "team",
    status: "not-started",
    progress: 0,
    ownerId: "emp-002",
    contributorIds: [],
    parentId: "sg-001",
    dueDate: "2026-06-30",
    assignation: "IT Domain",
    measureStart: 5000,
    measureTarget: 10000,
    measureCurrent: 0,
  },
  {
    id: "sg-006",
    title: "Platform Domain ARR",
    description: "Drive ARR growth in the Platform domain (API, Integrations, Workflows).",
    level: "team",
    status: "on-track",
    progress: 55,
    ownerId: "emp-014",
    contributorIds: ["emp-013"],
    parentId: "sg-001",
    dueDate: "2026-05-20",
    assignation: "Platform Domain",
    measureStart: 8000,
    measureTarget: 15000,
    measureCurrent: 11850,
  },

  // ── Individual goals under Finance Domain ────────────────────────────

  {
    id: "sg-009",
    title: "Optimize sales performance",
    description: "Improve conversion rates and reduce sales cycle in Finance products.",
    level: "individual",
    status: "at-risk",
    progress: 40,
    ownerId: "emp-005",
    contributorIds: [],
    parentId: "sg-003",
    dueDate: "2026-04-18",
    assignation: "Finance Domain",
    measureStart: 10000,
    measureTarget: 18000,
    measureCurrent: 13200,
  },
  {
    id: "sg-010",
    title: "Bugs",
    description: "Reduce critical bug count in Finance domain products.",
    level: "individual",
    status: "in-progress",
    progress: 65,
    ownerId: "emp-006",
    contributorIds: [],
    parentId: "sg-003",
    dueDate: "2026-05-09",
    assignation: "Finance Domain",
    measureStart: 0,
    measureTarget: 50,
    measureCurrent: 32,
  },

  // ── Team-level: CX target children ───────────────────────────────────

  {
    id: "sg-016",
    title: "Upsell 2M in Q1",
    description: "Close 2M in upsell revenue during Q1.",
    level: "team",
    status: "overachieved",
    progress: 120,
    ownerId: "emp-010",
    contributorIds: [],
    parentId: "sg-015",
    dueDate: "2026-04-10",
    assignation: "CX team",
    measureStart: 0,
    measureTarget: 2000,
    measureCurrent: 2400,
  },
  {
    id: "sg-017",
    title: "Upsell 3M in Q2",
    description: "Close 3M in upsell revenue during Q2.",
    level: "team",
    status: "in-progress",
    progress: 35,
    ownerId: "emp-010",
    contributorIds: [],
    parentId: "sg-015",
    dueDate: "2026-06-22",
    assignation: "CX team",
    measureStart: 0,
    measureTarget: 3000,
    measureCurrent: 1050,
  },
  {
    id: "sg-018",
    title: "Upsell 5M in Q3",
    description: "Close 5M in upsell revenue during Q3.",
    level: "team",
    status: "not-started",
    progress: 0,
    ownerId: "emp-010",
    contributorIds: [],
    parentId: "sg-015",
    dueDate: "2026-06-30",
    assignation: "CX team",
    measureStart: 0,
    measureTarget: 5000,
    measureCurrent: 0,
  },

  // ── Individual goals under Upsell 5M in Q3 ──────────────────────────

  {
    id: "sg-019",
    title: "Optimize sales performance",
    description: "Improve upsell conversion through better tooling and playbooks.",
    level: "individual",
    status: "not-started",
    progress: 0,
    ownerId: "emp-003",
    contributorIds: [],
    parentId: "sg-018",
    dueDate: "2026-06-12",
    assignation: "Emma Sesmero",
    measureStart: 0,
    measureTarget: 2500,
    measureCurrent: 0,
  },
  {
    id: "sg-020",
    title: "Streamline internal processes",
    description: "Reduce manual steps in the CX upsell workflow.",
    level: "individual",
    status: "not-started",
    progress: 0,
    ownerId: "emp-003",
    contributorIds: [],
    parentId: "sg-018",
    dueDate: "2026-05-25",
    assignation: "Emma Sesmero",
    measureStart: 0,
    measureTarget: 2500,
    measureCurrent: 0,
  },
]
