import type { PrototypeMeta, PrototypeModule } from "./types"

/**
 * Auto-discovers prototypes by globbing `src/prototypes/<slug>/<Slug>.tsx`.
 * Each prototype module exports `meta` (typed as PrototypeMeta) and a default
 * React component. The framework reads them to populate the catalog and
 * resolve the /p/:slug route.
 *
 * Designers do not edit this file. They just create a new folder with a
 * compliant `meta` + default export and the prototype shows up automatically.
 */
const modules = import.meta.glob("./*/*.tsx", { eager: true }) as Record<
  string,
  PrototypeModule
>

export type PrototypeRegistryEntry = {
  component: React.ComponentType
  meta: PrototypeMeta
  sidebar?: React.ComponentType
}

export const prototypeRegistry: Record<string, PrototypeRegistryEntry> =
  Object.fromEntries(
    Object.values(modules)
      .filter(
        (mod): mod is PrototypeModule =>
          typeof mod === "object" &&
          mod !== null &&
          "meta" in mod &&
          "default" in mod
      )
      .map((mod) => [
        mod.meta.slug,
        { component: mod.default, meta: mod.meta, sidebar: mod.sidebar },
      ])
  )

export const allPrototypes: PrototypeMeta[] = Object.values(
  prototypeRegistry
).map((entry) => entry.meta)
