name: "Publish to npmjs"

inputs:
  workspace:
    description: "Workspace"
    required: true
  registry_token:
    description: "Registry token"
    required: true

outputs:
  published:
    description: "Published packages"
    value: ${{ steps.publish.outputs.published }}

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-node-pnpm
      name: Setup Node and pnpm

    - name: Build
      shell: bash
      run: |
        pnpm --filter @factorialco/f0-core build
        pnpm --filter ${{ inputs.workspace }} build

    - name: Publish to registry
      shell: bash
      id: publish
      run: |
        result=$(pnpm --filter ${{ inputs.workspace }} publish --no-git-checks --access=public)
        if [[ $result == "There are no new packages that should be published" ]]
        then
          echo "No new packages to publish"
          echo "published=false" >> $GITHUB_OUTPUT
        else
          echo "Packages published"
          echo "published=true" >> $GITHUB_OUTPUT
        fi
      env:
        NODE_AUTH_TOKEN: ${{ inputs.registry_token }}
