name: "Publish to npmjs"

inputs:
  workspace:
    description: "Workspace"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      shell: bash
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.release.tag_name || github.event.inputs.release_tag || github.sha }} # Checkout the tagged release

    - uses: ./.github/actions/setup-node-pnpm
      shell: bash
      name: Setup Node and pnpm

    - name: Build
      shell: bash
      run: |
        pnpm --filter @factorialco/factorial-one-core build
        pnpm --filter ${{ inputs.workspace }} build

    - name: Publish to registry
      shell: bash
      run: pnpm --filter ${{ inputs.workspace }} publish --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
