name: "Publish to npmjs"

inputs:
  workspace:
    description: "Workspace"
    required: true
  registry_token:
    description: "Registry token"
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-node-pnpm
      name: Setup Node and pnpm

    - name: Build
      shell: bash
      run: |
        pnpm --filter @factorialco/factorial-one-core build
        pnpm --filter ${{ inputs.workspace }} build

    - name: Publish to registry
      shell: bash
      run: pnpm --filter ${{ inputs.workspace }} publish --no-git-checks --access=public
      env:
        NODE_AUTH_TOKEN: ${{ inputs.registry_token }}
