name: "Check workspaces changes"
on:
  workflow_call:
    outputs:
      package_react:
        description: "Changes in the react package"
        value: ${{ jobs.changes.outputs.package_react }}
      package_react_native:
        description: "Changes in the react-native package"
        value: ${{ jobs.changes.outputs.package_react_native }}

jobs:
  # Detect which projects have changed
  changes:
    name: Check for workspaces with changes
    runs-on: ubuntu-latest
    outputs:
      package_react: ${{ steps.changes.outputs.package_react }}
      package_react_native: ${{ steps.changes.outputs.package_react_native }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          token: ${{ github.token }}
          # Add the paths to the packages you want to check for changes
          # If a package has dependencies in another package, you should include both like in the `package_react`
          # as we want to trigger the react package workflow's also when the core package changes
          filters: |
            package_react: 
              - 'packages/react/**/*'
              - 'packages/core/**/*'
              - '!.release-please-manifest.json'
              - '!packages/react/CHANGELOG.md'
              - '!packages/react/package.json'
            package_react_native: 
              - '!.release-please-manifest.json'
              - 'packages/react-native/**/*'
              - 'packages/core/**/*'
