name: "Check workspaces changes"
on:
  workflow_call:
    outputs:
      package_react:
        description: "Changes in the react package"
        value: ${{ jobs.changes.outputs.package_react }}
      package_react_native:
        description: "Changes in the react-native package"
        value: ${{ jobs.changes.outputs.package_react_native }}
      package_core:
        description: "Changes in the core package"
        value: ${{ jobs.changes.outputs.package_core }}

jobs:
  # Detect which projects have changed
  changes:
    name: Check for workspaces with changes
    runs-on: ubuntu-latest
    outputs:
      package_react: ${{ steps.changes.outputs.package_react }}
      package_react_native: ${{ steps.changes.outputs.package_react_native }}
      package_core: ${{ steps.changes.outputs.package_core }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          token: ${{ github.token }}
          filters: |
            package_react: 
              - 'packages/react/**'
              - 'packages/core/**'
            package_react_native: 
              - 'packages/react-native/**'
            package_core: 
              - 'packages/core/**'
