name: Build and Publish [ALPHA]

on:
  issue_comment:
    types: [ created ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  publish-alpha:
    if: |
      (github.event_name == 'issue_comment' &&
       github.event.issue.pull_request &&
       contains(github.event.comment.body, 'build')) ||
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/setup-node-pnpm
        name: Setup Node and pnpm

      - name: Build
        run: pnpm build

      - name: Publish to release branch npm/alpha-pr-${{ github.event.pull_request.number }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Publish alpha version
          pnpx git-publish -b 'npm/alpha-pr-${{ github.event.pull_request.number }}'
          LAST=$(git rev-parse HEAD)
          echo "::notice title='Package published'::Use pnpm i github:factorialco/factorial-one#npm/alpha-pr-${{ github.event.pull_request.number }} to install the package (or pnpm i github:factorialco/factorial-one#${LAST} to install this specific commit)"
 

