name: Build and Publish [STABLE]

on:
  push:
    branches:
      - main
  issue_comment:
    types: [ created ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  test222:
    runs-on: ubuntu-latest
    steps:
      - name: Test2222
        run: |
          echo "Testing..."
          exit 0
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          target-branch: chore/publish-as-package

  publish-npm:
    needs: release-please
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: ${{ needs.release-please.outputs.release_created }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Setup Node and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Build
        run: pnpm build

      - name: Publish to registry
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

