name: Build and Publish [STABLE]

on:
  push:
    branches:
      - main
  issue_comment:
    types: [ created ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      BRANCH: chore/publish-as-package # ${{ github.event.repository.default_branch }}
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      pr: ${{ steps.release.outputs.pr }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          target-branch: ${{ env.BRANCH }}

      - run: gh pr merge $PR_NUMBER --squash --admin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ fromJSON(steps.release.outputs.pr).number }}

  publish-npm:
    needs: [ release-please ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: ${{ needs.release-please.outputs.prs_created }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Setup Node and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Build
        run: pnpm build

      - name: Publish to registry
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup PR alpha versions
        uses: ./.github/actions/cleanup-alpha-versions
        if: ${{ github.event.pull_request.number }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }} # PR that triggered the workflow

