name: "Build and Publish Storybook to GitHub Pages"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  PUBLIC_BUILD: true

jobs:
  # Detect which projects have changed
  detect-changes:
    uses: ./.github/workflows/_check-workspaces-changes.yaml

  deploy:
    needs: detect-changes
    name: "[⚛️ REACT] Deploy Storybook to GitHub Pages"
    # Prevents running on the release-please branch
    if: |
      needs.detect-changes.outputs.package_react == 'true' &&
      github.head_ref != 'release-please--branches--master' &&
      !contains(github.event.pull_request.labels.*.name, 'autorelease')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
      - run: pnpm --filter @factorialco/factorial-one-core build
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: pnpm install
          build_command: pnpm --filter @factorialco/factorial-one-react run build-storybook
          path: packages/react/storybook-static
