name: "Build and Publish Storybook to Azure Static Web Apps"

on:
  push:
    branches:
      - "main"
      - "chore/azure-deploy" # TODO: Remove this branch. Was created to test the Azure deployment.
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  PUBLIC_BUILD: true

jobs:
  # Detect which projects have changed
  detect-changes:
    uses: ./.github/workflows/_check-workspaces-changes.yaml

  deploy:
    needs: detect-changes
    name: "[⚛️ REACT] Deploy Storybook to Azure Static Web Apps"
    # Prevents running on the release-please branch
    if: |
      needs.detect-changes.outputs.package_react == 'true' &&
      github.head_ref != 'release-please--branches--master' &&
      !contains(github.event.pull_request.labels.*.name, 'autorelease')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node and PNPM
        uses: ./.github/actions/setup-node-pnpm

      - name: Install dependencies
        run: |
          sed -i 's/"workspace:\*"/"latest"/g' packages/react/package.json
          pnpm install --no-frozen-lockfile

      - name: Build Core
        run: pnpm --filter @factorialco/factorial-one-core build

      - name: Build Storybook
        run: pnpm --filter @factorialco/factorial-one-react run build-storybook

      - name: Deploy Storybook to Azure
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          skip_app_build: true
          app_location: packages/react/storybook-static
