name: "Chromatic"

on:
  pull_request:
  push:
    branches:
      - main

env:
  PUBLIC_BUILD: true

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  chromatic:
    permissions: write-all
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: pnpm
      - run: pnpm install
      - name: Run Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: "main"
          exitOnceUploaded: true

      - name: Publish Storybook Link in the comments
        if: github.event_name == 'pull_request'
        uses: dannyhw/storybook-chromatic-link-comment@v0.10
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-url: ${{ steps.chromatic.outputs.url }}
          build-url: ${{ steps.chromatic.outputs.buildUrl }}
          storybook-url: ${{ steps.chromatic.outputs.storybookUrl }}
