name: Publish factorial-one package to npm

on:
  release:
    types: [ released, created, published ]
  # Release is not triggered when the release was created by another workflow using GITHUB_TOKEN https://github.com/orgs/community/discussions/25281#discussioncomment-3300251
  workflow_run:
    workflows: [ Create release ]
    types:
      - completed

  workflow_dispatch: # Allows manual triggering
    inputs:
      release_tag:
        description: 'The release tag to checkout'
        required: true

jobs:
  publish:
    if: |
      github.event_name == 'workflow_dispatch' || github.event_name == 'release' || 
      (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.outputs.new_version)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.event.inputs.release_tag || github.sha }}  # Checkout the tagged release

      - uses: ./.github/actions/setup-node-pnpm
        name: Setup Node and pnpm

      - name: Build
        run: pnpm build

      - name: Publish to registry
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
