name: "[REACT] Build and Publish Storybook to GitHub Pages"

on:
  push:
    branches:
      - "main"
    paths:
      - packages/react/**/*
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  PUBLIC_BUILD: true

jobs:
  deploy:
    name: Deploy Storybook to GitHub Pages
    # Prevents running on the release-please branch
    if: "github.head_ref != 'release-please--branches--master' && !contains(github.event.pull_request.labels.*.name, 'autorelease')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: pnpm install
          build_command: pnpm --filter @factorialco/factorial-one-react run build-storybook
          path: storybook-static
