name: Create release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      BRANCH: ${{ github.event.repository.default_branch }}
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      pr: ${{ steps.release.outputs.pr }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          target-branch: ${{ env.BRANCH }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Merge PR
        run: |
          gh auth status
          if [ -z "$PR_NUMBER" ]; then
            echo "No PR number found"
            echo "::warning title='No release PR created by release-please'::Conventional commits didnt triggeer a version bump and release is not necessary"
            exit 0
          fi
          gh pr merge $PR_NUMBER --squash --admin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ fromJSON(steps.release.outputs.pr || '{}').number }}
