name: "Remove old alpha release branches"

on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: 'Pull Request Number'
        required: true
        type: number
      days:
        description: 'Number of days to keep (default: 5)'
        required: false
        type: number

jobs:
  clear-alpha-versions:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
    steps:
      - name: Remove old alpha release branches
        uses: ./.github/actions/cleanup-alpha-versions
        with:
          days: ${{ inputs.days }}
          pr-number: ${{ inputs.pr-number }}