name: "size"
on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Detect which projects have changed
  detect-changes:
    uses: ./.github/workflows/_check-workspaces-changes.yaml
  test:
    needs: detect-changes
    name: "[⚛️ REACT] Size"
    if: |
      needs.detect-changes.outputs.package_react == 'true' &&
      github.head_ref != 'release-please--branches--master' &&
      !contains(github.event.pull_request.labels.*.name, 'autorelease')
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          ## Set repository to correctly checkout from forks
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
      - uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: "22.x"
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build core package
        run: pnpm --filter @factorialco/factorial-one-core build
      - uses: andresz1/size-limit-action@94bc357df29c36c8f8d50ea497c3e225c3c95d1d
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: packages/react
          package_manager: pnpm
          script: size:ci
