name: "Unit Tests"
on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: "github.head_ref != 'release-please--branches--master' && !contains(github.event.pull_request.labels.*.name, 'autorelease')"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
      - uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: "22.x"
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build core package
        run: pnpm --filter @factorialco/factorial-one-core build
      - name: Run type checking
        run: pnpm run tsc
      - name: Run tests
        run: pnpm run vitest:ci
