name: "Unit Tests"
on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Detect which projects have changed
  detect-changes:
    uses: ./.github/workflows/_check-workspaces-changes.yaml
  test:
    needs: [detect-changes]
    name: "[⚛️ REACT] Unit Tests"
    if: |
      needs.detect-changes.outputs.package_react == 'true' &&
      github.head_ref != 'release-please--branches--master' &&
      !contains(github.event.pull_request.labels.*.name, 'autorelease') &&
      !(github.event_name == 'pull_request' && needs.check-main-coverage.outputs.has_coverage_main == 'true' && matrix.branch == 'main')
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: main
            artifact: main
          - branch: ${{ github.head_ref }}
            artifact: pull-request
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          ## Set repository to correctly checkout from forks
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
      - uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: "22.x"
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build core package
        run: pnpm --filter @factorialco/factorial-one-core build
      - name: Run type checking
        run: pnpm --filter @factorialco/factorial-one-react run tsc
      - name: Run tests
        run: pnpm --filter @factorialco/factorial-one-react run vitest:ci --coverage.enabled true
      - name: "Report Coverage"
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: packages/react
      - name: "Upload Coverage"
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.artifact }}
          path: packages/react/coverage

  report-coverage:
    needs: detect-changes
    name: "[⚛️ REACT] Report Coverage"
    if: |
      needs.detect-changes.outputs.package_react == 'true' &&
      github.head_ref != 'release-please--branches--master' &&
      !contains(github.event.pull_request.labels.*.name, 'autorelease')
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Download Coverage Artifacts"
        uses: actions/download-artifact@v4
        with:
          name: coverage-pull-request
          path: packages/react/coverage
      - uses: actions/download-artifact@v4
        with:
          name: coverage-main
          path: packages/react/coverage-main
      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-compare-path: packages/react/coverage-main/coverage-summary.json

  # ------------------------------------------------------------------------------

  test-react-native:
    needs: detect-changes
    name: "[📱 REACT NATIVE] Unit Tests"
    if: |
      needs.detect-changes.outputs.package_react_native == 'true'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
      - uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: "22.x"
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build core package
        run: pnpm --filter @factorialco/factorial-one-core build
      - name: Run tests
        run: pnpm --filter @factorialco/factorial-one-react-native run test
