name: "Unit Tests"
on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: github.head_ref != 'release-please--branches--master'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
      - name: Run type checking
        run: pnpm run tsc
      - name: Run tests
        run: pnpm run vitest:ci
